### ISSUE TITLE
Need to get bucket details in storage.create

### ISSUE THREAD

**Issue by RuchaPurandare** [GoogleCloudPlatform/google-cloud-go#1038]
I am trying to use the storage library to create a bucket. I need to get all bucket details like userProject, predefinedAcl. I found that we can only create a bucket and get a set of its attributes. Is there any way we can get the userProject/predefinedAcl  from the newly created bucket? I am trying to create a response that matches with the create bucket JSON API.

Environment:
go 1.10.2
google-cloud-go v0.22.0

**Comment by jba** [comment]
I'm not exactly sure what you're asking. Are there fields of a [bucket resource](https://cloud.google.com/storage/docs/json_api/v1/buckets#resource) that we not exposing? Let us know which so we can add them. I don't see userProject or predefinedAcl on that page.

**Comment by RuchaPurandare** [comment]
Yes create bucket is allowing only limited fields. I have highlighted the ones I couldn't find.
Also currently we get no response object on bucket creation. It would be nice to have the details of created bucket in response. 
[GoogleCloud-CreateBucket.xlsx](https://github.com/GoogleCloudPlatform/google-cloud-go/files/2126273/GoogleCloud-CreateBucket.xlsx)

**Comment by jba** [comment]
Predefined ACLs is #61.  I've added logging as #1041, website as #1042, and the ACL fields as #1043. I'll try to get to all of these in the next few weeks.

We can't change the return type of `BucketHandle.Create`, unfortunately, because it would be a breaking change. Since we don't return attrs from `Create`, the `projection` field doesn't make sense. You can always call `BucketHandle.Attrs` immediately afterwards.

**Comment by RuchaPurandare** [comment]
We were planning to use the library for one of our releases. Can you provide tentative date or version in which these changes will be available?

**Comment by jba** [comment]
I can't give an exact date, but six weeks is a conservative estimate. I'll try to do it sooner.

Your team is welcome to contribute&mdash;the code is open-source, and these features are quite straightforward. See [CONTRIBUTING.md](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/CONTRIBUTING.md) for details.

**Comment by jba** [comment]
All the dependent bugs are done, so I'm closing this.

Rereading your original message, I see that you want to recover the predefinedAcl field from a bucket. That's not possible, because there's no such field. When you specify a predefined ACL on bucket creation, Google Cloud Storage expands the string you provide into an ACL. The string itself is not stored anywhere.

You can attempt to reverse-engineer the predefined ACL string by scanning the ACL. See [this test](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/e615d33101b4ccf8ef205a981ac768c3a6a78d61/storage/integration_test.go#L2232) for inspiration.
