### ISSUE TITLE
bigtable: cbt application profile should match gcloud

### ISSUE THREAD

**Issue by sduskis** [GoogleCloudPlatform/google-cloud-go#1057]
GCloud `app_profile create` has this specification:

> gcloud beta bigtable app-profiles create (APP_PROFILE : --instance=INSTANCE) (--route-any     | [--route-to=ROUTE_TO : --transactional-writes]) [--description=DESCRIPTION] [--force] [GCLOUD_WIDE_FLAG …]

cbt has this specification:

> cbt createappprofile `<instance-id>` `<profile-id>` `<description>` `<etag>` `<routing-policy>` [cluster-id=`<cluster-id>`] [allow-transactional-writes=`<allow-transactional-writes>`]

gcloud `app_profile update` has this specification:

> gcloud beta bigtable app-profiles update (APP_PROFILE : --instance=INSTANCE) [--async] [--description=DESCRIPTION] [--force] [--route-any     | [--route-to=ROUTE_TO : --transactional-writes]] [GCLOUD_WIDE_FLAG …]

cbt has this specification:

> cbt updateappprofile  `<instance-id>` `<profile-id>` `<description>` `<routing-policy>` [cluster-id=`<cluster-id>`] [allow-transactional-writes=<allow-transactional-writes>]

Ideally, cbt should look more like gcloud.  TODO, at the very least:
- [ ] remove etag from cbt
- [ ] add the ability to "--force" which translates to setting `ignore_warnings` = `true` in the protobuf.
- [ ] `--route-any` and `--route-to=[clusterId]` would be really nice.

**Comment by jba** [comment]
Removing `etag` and `routing-policy` are breaking changes. Are you OK with breaking these commands? Do you need to communicate the breaking changes to users?

I agree that `etag` should be removed from `createappprofile`, because it makes no sense there. (You can't set an ETag if the resource doesn't exist.)  But `updateappprofile` should have an `etag` option, so cbt users can safely perform read-modify-write cycles.

**Comment by sduskis** [comment]
My expectation is that most users will be using gcloud, so I'm ok with breaking changes.

`etag` is not actually used even implemented in `updateappprofile` in the Cloud Bigtable service.
