### ISSUE TITLE
How can multiple clients use the speech service and how are streams billed?

### ISSUE THREAD

**Issue by SephVelut** [GoogleCloudPlatform/google-cloud-go#1064]
On the same machine, same process, how can I get multiple instances of a bidirectional streaming rpc call? Particularly for the Google Speech streaming recognize api.

At the moment I'm doing
```
client, err := speech.NewClient(context)
stream, err := client.StreamingRecognize(context)
```

for each stream of audio I want to process. I don't want to reuse any connection. Each stream is a different processing context. The problem arises when I attempt to clean up after any individual stream
`stream.CloseSend()` which somehow effects all other instances of `client` and `stream` that I create separately. I receive EOF error on all of them, even though I assumed they were separate. Even worse when I `client.Close()` then any future connections result in `rpc error: code = Canceled desc = grpc: the client connection is closing`

Between figuring out channels, grpc's internal load balancer and the go Context, I just can't figure out where to begin. Is some connection somewhere being reused? If so how can I disable that? And if there is a difference between connection/channel/client/stream, which one is billable?

**Comment by jba** [comment]
Couldn't reproduce. I ran three streams concurrently from the same client. When the first called CloseSend, the others continued unaffected.

Then I closed the client, opened a new one, and did it again. Everything was fine.

Can we see your code?

**Comment by SephVelut** [comment]
Sorry I should have posted a reproducible gist. I'll extract out the relevant code and post it. In the meantime, when I  `speech.NewClient(context)` that is dialing google cloud, opening a connection, not a 'grpc channel' and keeping it open for future channels initiated by `client.StreamingRecognize(context)`? My other question is `NewClient` by itself billable? Google cloud docs say that a streaming request falls under 15 second repeating charge. Is that just for `client.StreamingRecognize(context)`?

**Comment by jba** [comment]
`NewClient` probably doesn't do anything; by default, gRPC connections are dialed lazily at the first RPC.

I don't know whether subsequent calls to `StreamingRecognize` use new HTTP/2 channels in the same TCP connection, or start a new connection. But that shouldn't affect how you perceive `CloseSend` or `Client.Close`.

What I say about billing is just my understanding of the [Speech-To-Text API Pricing page](https://cloud.google.com/speech-to-text/pricing). You should confirm with GCP support.

- There is no charge for `NewClient`, since you're not processing any audio.
- You're billed by the amount of processed audio, regardless of which RPC you call to do so. Corollaries:
  - `CloseSend` will stop billing, but so will not calling `CloseSend` and just not transmitting any more data.
  - If you send one minute of audio in (a) a single stream, (b) split across two streams from the same client, or (c) split across two streams each from a different client, it won't matter: you'll be billed for one minute of processing.
- I don't see anything on that page about "a streaming request falls under 15 second repeating charge". Can you clarify what that means and where you saw it?

**Comment by SephVelut** [comment]
By repeating charge I mean if the bill is $0.006 for 15 seconds of audio then 30 seconds will be $0.006 * 2. Every 15 seconds of audio is another charge, hence repeating.

My understanding is that because google rounds up to 15 seconds `Each request is rounded up to the nearest increment of 15 seconds`, it could actually end up being more than a one minute charge if you split an audio recording up between streams. I'll explain, given 60 seconds of audio:

stream 1 processes -> 16 seconds of audio and is charged $0.006 * 2 (16 seconds rounded to a 30 second charge. Each 15 seconds is a charge so we multiply by 2

stream 2 processes -> 44 seconds of audio and is charged $0.006 * 4 (44 seconds rounded to 60 second charge. Each 15 seconds is a charge so we multiply by 4

Due to the rounding this results in an extra charge (total of $0.006 * 5) whereas if only one stream sent the audio

stream 1 processes -> 60 seconds and is charged (total of $0.006 * 4)

This is essentially what I'm trying to solve. A bin packing sort of problem for a pool of preempted google speech streams. Preempted because we need them to process audio immediately after a request and ~200 - 500 millisecond wait for each new connection cant be tolerated. This obviously results in us having to send "empty" audio data to Google Speech to keep the connection open while we wait for real audio, otherwise GRPC errors out with `audio is being streamed too slow`. The costs my company are incurring are really really high right now and its important I understand what is being charged exactly.

**Comment by jba** [comment]
You're quite right, because of rounding up it can matter how  you divide the audio. And the pricing page does talk about "requests," which is not clear in the streaming case. Anything else I say would be speculation, so please contact GCP support.

**Comment by SephVelut** [comment]
I'll close this issue until I can readdress the original question with example and reopen. I will follow up with GCE support regarding some of the ambiguities as well.
