### ISSUE TITLE
Storage: possible data corruption if a HTTP/2 streaming error occurs while an object is changed

### ISSUE THREAD

**Issue by nomis52** [GoogleCloudPlatform/google-cloud-go#1106]
See the comment on https://code-review.googlesource.com/c/gocloud/+/25630

**Comment by jba** [comment]
Copying the comment from the CL:

> There looks like a bug here. The retry calls to reopen() don't include the generation number from the headers of the first response. If a new generation of the object is uploaded between the first call and the retry we'll end up concatenating data from two different generations. I haven't experienced this - I was looking at the code and noticed it.

**Comment by jba** [comment]
Actually, if a specific generation number is set, a `generation=N` query parameter will be the URL of all requests, so that case is OK.

The problem is when you don't specify a generation number. Unfortunately, I don't think GCS returns a generation number in the response. But it does return an Etag header, and we should be able to use that in an If-Match header in subsequent requests.

Reference: https://cloud.google.com/storage/docs/xml-api/get-object-download.

**Comment by nomis52** [comment]
The generation is returned in a header from GCS:

```
X-Goog-Generation:[123455]
X-Goog-Metageneration:[1]
```

https://cloud.google.com/storage/docs/xml-api/reference-headers#xgooggeneration

**Comment by jadekler** [comment]
https://code-review.googlesource.com/c/gocloud/+/31950
