### ISSUE TITLE
cbt "count" command from cloud shell does not return any result

### ISSUE THREAD

**Issue by pranay29** [GoogleCloudPlatform/google-cloud-go#1112]
## Client

BigTable

## Describe Your Environment

When running the command from cloud shell `cbt -project projectX -instance instanceX count tablename`

## Expected Behavior

Command should return the count of records in `tablename`

## Actual Behavior

Nothing is returned/printed on the console

**Comment by tylerdmace** [comment]
Also seeing this behavior.

**Comment by garye** [comment]
See #1099 - this needs a cloud sdk release.

**Comment by pranay29** [comment]
I ran `gcloud components update ` command from cloud shell. However `cbt` still does not return the count.

**Comment by tylerdmace** [comment]
@pranay29 You're running the glcloud version of `cbt`. You need to use the go package and run it from there.

For example, I use:

```$ /home/tyler/go/bin/cbt -instance X count Y```

**Comment by pranay29** [comment]
Thank you @tylerdmace .

Though I feel that the `gcloud` version of `cbt` should also return the result.

**Comment by sduskis** [comment]
@pranay29, you are correct.  The `gcloud` version of `cbt` should also return the result.  We need to create a new release of cbt, and package it into a new version of gcloud; this will fix the problem in gcloud as well.  This issue was to track the first part of the problem, which was fixing the code in this repository.  We are actively working on a new release of `cbt` in `gcloud`.

**Comment by garye** [comment]
This is fixed in Cloud SDK 214.0.0.
https://cloud.google.com/sdk/docs/release-notes
