### ISSUE TITLE
Consider using `sql.NullXXX` instead of `spanner.NullXXX` types

### ISSUE THREAD

**Issue by bmhatfield** [GoogleCloudPlatform/google-cloud-go#1117]
## Client

Spanner

## Expected Behavior

It's easy to use Nullable types in a variety of situations

## Actual Behavior

It's very difficult to use Nullable types in a variety of situations

# Request/Recommendation

Consider converting the Spanner client to use sql.NullXXX types. This allows folks implementing Spanner in a "generic" way to use a common nullable type, which benefits type switches in other packages (say, adding support to go-graphql). Currently `spanner` using custom Nullable types couples implementations tightly to spanner, when that's not truly needed as a set of Nullable types exists in the standard library.

Here's a link to the Standard Library nullable types: https://golang.org/pkg/database/sql/#NullString.

It appears that Spanner implements a superset of these types, but I am hopeful that some compromise can be made for these very common base types.

**Comment by jba** [comment]
I don't see how we can do this. The sql types are tied to the sql packages. For instance, the `Value` method returns a `driver.Value`.

Some sort of adapter between this client and `database/sql` might be possible; we haven't thought about it. I think we'd want to do that instead of just focusing on the nullable types.
