### ISSUE TITLE
pubsub: lease behaviour

### ISSUE THREAD

**Issue by nfisher** [GoogleCloudPlatform/google-cloud-go#1144]
Apologies not sure this is the correct location to post this but I'm using the Go library to verify pubsubs lease behaviour and I'm not sure how much of what I'm seeing is library vs service based. I suspect it's more related to the latter in which case if you can guide me to the best forum to ask about this it would be appreciated! 😄refs google/go-cloud/issues/432

#### Client

pubsub

#### What did you do?
 
1. Created 1 publisher which publishes a single message to a topic containing a single subscription with a 60s ack deadline.
2. Created 2 subscribers P1 and P2 which subscribe to the above topic/subscription.
3. P1 starts, receives message, and dies (log.Fatal) 10s after startup and prior to ack'ing the message.
4. P2 starts [sub.Receive](https://godoc.org/cloud.google.com/go/pubsub#Subscription.Receive) callback loop ~10s after P1 startup.
5. P2 receives message after P1 dies.

#### What did you expect to see?

For step 5 I expected to see P2 receive the message close to the "ack deadline" less the 10s delay.

#### Reproducible test case

https://github.com/fresh8/domsub/
Run `GOOGLE_PROJECT_ID=YOUR_PROJECT make s2` replacing YOUR_PROJECT with an appropriate GCP project.

#### What did you see instead?

The message was received ~10s after P1 died.

Below is an example output from `make s2` run outlined in the reproducible test case.
```
$ make s2
# <!-- snip drain and publish -->

# <!-- P1 starts at 01:53:57 -->
2018/09/12 01:53:57 main.go:34: starting subscriber b9954b24b1af4fcf9bbfde92904e26ad
[b9954b24b1af4fcf9bbfde92904e26ad] 2018/09/12 01:53:57 main.go:37: subscribing to scenario fresh-8-staging domsub
[b9954b24b1af4fcf9bbfde92904e26ad] 2018/09/12 01:53:57 main.go:48: sleep before starting for 0s
[b9954b24b1af4fcf9bbfde92904e26ad] 2018/09/12 01:53:57 main.go:58: sleep before stop for 10s
[b9954b24b1af4fcf9bbfde92904e26ad] 2018/09/12 01:53:57 main.go:73: sleep before ack for 30s
[b9954b24b1af4fcf9bbfde92904e26ad] 2018/09/12 01:53:57 main.go:97: entering receive loop
# <!-- P1 receives message at 01:54:02 -->
[b9954b24b1af4fcf9bbfde92904e26ad] 2018/09/12 01:54:02 main.go:99: received 203633335783895 hola señor!
# <!-- P1 dies at 01:54:07 -->
[b9954b24b1af4fcf9bbfde92904e26ad] 2018/09/12 01:54:07 main.go:61: Yippee ki-yay

# <!-- P2 starts at 01:53:57 (same time as P1) -->
2018/09/12 01:53:57 main.go:34: starting subscriber dfa34cd9a1bb44c1ac12fbd9881adbdd
[dfa34cd9a1bb44c1ac12fbd9881adbdd] 2018/09/12 01:53:57 main.go:37: subscribing to scenario fresh-8-staging domsub
[dfa34cd9a1bb44c1ac12fbd9881adbdd] 2018/09/12 01:53:57 main.go:48: sleep before starting for 10s
[dfa34cd9a1bb44c1ac12fbd9881adbdd] 2018/09/12 01:54:07 main.go:58: sleep before stop for 1m0s
[dfa34cd9a1bb44c1ac12fbd9881adbdd] 2018/09/12 01:54:07 main.go:73: sleep before ack for 0s
[dfa34cd9a1bb44c1ac12fbd9881adbdd] 2018/09/12 01:54:07 main.go:75: entering ack loop
[dfa34cd9a1bb44c1ac12fbd9881adbdd] 2018/09/12 01:54:07 main.go:97: entering receive loop

# <!-- P2 receives message 11s after P1 died at 01:54:07 -->
[dfa34cd9a1bb44c1ac12fbd9881adbdd] 2018/09/12 01:54:18 main.go:99: received 203633335783895 hola señor!
[dfa34cd9a1bb44c1ac12fbd9881adbdd] 2018/09/12 01:54:18 main.go:88: acking 203633335783895 hola señor!
[dfa34cd9a1bb44c1ac12fbd9881adbdd] 2018/09/12 01:55:07 main.go:65: canceling context
[dfa34cd9a1bb44c1ac12fbd9881adbdd] 2018/09/12 01:55:07 main.go:102: left receive loop
[dfa34cd9a1bb44c1ac12fbd9881adbdd] 2018/09/12 01:55:07 main.go:92: left ack loop
```

Does this mean that in addition to "ack deadline" pubsub also uses TCP teardown for lease expiration? I didn't see an obvious reference to this behaviour in the documentation here;

* https://cloud.google.com/pubsub/docs/pull
* https://cloud.google.com/pubsub/docs/faq

The reason I ask is that I would like to ensure other delays like GC won't lead to a lease expiry in a similar fashion to what was discovered above.

#### System details

```
go version go1.11 darwin/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/nathanfisher/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/nathanfisher/workspace/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
GOROOT/bin/go version: go version go1.11 darwin/amd64
GOROOT/bin/go tool compile -V: compile version go1.11
uname -v: Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G65
lldb --version: lldb-902.0.79.7
  Swift-4.1
```

**Comment by jadekler** [comment]
Hi - thanks for reaching out.

> What did you see instead?
> The message was received ~10s after P2 died.

Is this accurate, or did you mistype P2 instead of P1? If it is accurate: could you describe this further? When did P2 die? Who received the message? (if P1 and P2 are dead).

> Does this mean that in addition to "ack deadline" pubsub also uses TCP teardown for lease expiration?

I believe not. The server will wait the leased time.

_However_, this issue brings up the fact that some of our documentation is out of date. We recently changed the subscriber to not look at `SubscriptionConfig.AckDeadlineSeconds`, which reduces the amount of permissions required to use the subscriber. The end result is as follows: The subscriber will immediately send a ModAck (modify ack deadline request) to the server when it receives a message, resetting its ack deadline to 10m (maximum time). Then, it periodically sends ModAcks to reset the ack deadline to a more reasonable number. The period and length of these extensions is based on a time distribution [1].

The long and short of that is:

- I should go update our documentation.
- You should not worry about setting AckDeadline if you're using our Receive() call, because the streaming pull subscriber (Receive() call) does not use it, preferring instead to use the distribution [1]. However, you might choose to set it if you use a different client (the PHP client, for example), or if you choose not to use streaming pull and prefer to use [synchronous pull](https://godoc.org/cloud.google.com/go/pubsub/apiv1#example-SubscriberClient-Pull-LengthyClientProcessing).
- The message being re-sent 10s after P1 (assuming you meant P1, not P2) is expected.

1: There is a distribution in which we record the time it took for each message to be acked. When we go to extend in-flight messages, we extend it by the 99%th value of this distribution. This has the effect that subscribers which process messages quickly have their message ack deadlines extended for a short amount, whereas subscribers which process message slowly have their message ack deadlines extended for a large amount. The net effect is less RPCs sent from the client library as well as less permissions needed to run the subscriber (we don't have to look at the value of SubscriptionConfig.AckDeadlineSeconds).

**Comment by jba** [comment]
> 1. If GC or similar occurs that exceeds the lease I assume duplicate message processing is likely to occur?

Yes, but we give ourselves a few seconds' grace, so this is unlikely.

> 2. How quickly does the client start adjusting the lease duration based on latency after start-up? 

We adjust it every 5 seconds.

> Is there a minimum number of samples required in the distribution?

No.

> 3. How does it adapt to network congestion and similar where latency increases?

**Comment by nfisher** [comment]
Great thanks for that! Feel free to close unless @jadekler is using this for tracking documentation updates.
