### ISSUE TITLE
case insensitive comparison for storage IAM member matching

### ISSUE THREAD

**Issue by alan-ma-umg** [GoogleCloudPlatform/google-cloud-go#1172]
@jba 

https://github.com/GoogleCloudPlatform/google-cloud-go/blob/75277bda5d3c8b70db834d93e176c6044916e3b0/iam/iam.go#L286

I'd propose to make the string comparison case insensitive. We have use cases that user's emails in all different casing: all uppercase, all lower case, or camelcase. With current implementation of memberIndex, same user with different casing won't match.

Thanks for your attention.

Alan

**Comment by jba** [comment]
We wouldn't be able to change the behavior because it could break existing clients who depend on case-sensitivity.

I also wouldn't want to add separate `Add`, `Remove` and `HasRole` methods that do case-insensitive comparison. That would bloat the package surface.

Instead, you can easily implement your own case-insensitive methods using the `Members` method. You can build your own case-insensitive `memberIndex` function from that. Use it directly for your version of `HasRole`. For `Add`, check for membership first with your `memberIndex`, then call the existing `Add` if it isn't present. To remove, use your `memberIndex` to look up the actual spelling of the member, then call the existing `Remove`.

**Comment by alan-ma-umg** [comment]
Thanks @jba. Make sense to me. Will do.
