### ISSUE TITLE
datastore: document use of local development server

### ISSUE THREAD

**Issue by hjfreyer** [GoogleCloudPlatform/google-cloud-go#126]
The documentation for gcd only gives examples for Java and Python, both of which are configured automagically via environment variables. I tried writing:

    http, err := cloud.DialHTTP(context.Background(), cloud.WithEndpoint("localhost:8080"))

But that gave the error:

    google.DefaultTokenSource: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

That page doesn't discuss local debugging at all.

**Comment by okdave** [comment]
Need to double check, but I think Python/Java use `DATASTORE_HOST` and `DATASTORE_DATASET` for auto configuration

**Comment by flowlo** [comment]
I'm developing an application that facilitates both Google App Engine (Managed VM, Go) and Google Compute Engine (Go) and accesses Datastore from both sides.

This works fine in production, although I am struggling a bit to get a nice testing and fiddling setup to run. It might be the case that this is just because of the apparent lack of documentation, so I will explain what we are trying here. If this is off topic, I would appreciate if you could direct me to the correct issue tracker/mailing list/whatever. Thank you.

When trying to let my code for Compute Engine connect to the local Datastore instance (started by `gcloud preview app run ...` or maybe also `gcd.sh`) I run into problems because I am not sure how to redirect requests to the local instance. I looked up `cloud.DialHTTP`, which says ["Most developers should call the relevant NewClient method for the target service rather than invoking DialHTTP directly."](https://github.com/GoogleCloudPlatform/gcloud-golang/blob/4c0ceacd6ba6cfe20aaa9ced25c65a2dd0aae7c1/internal/transport/dial.go#L21-L22) so I looked further and found [`datastore/example_test.go` which calls datastore.NewClient](https://github.com/GoogleCloudPlatform/gcloud-golang/blob/master/datastore/example_test.go#L47) which is [missing from the current version](https://godoc.org/google.golang.org/cloud/datastore). I also found [this answer on StackOverflow](http://stackoverflow.com/a/21865365) which talks about writing my own wrapper and accessing a `gcd.sh` Datastore instance. It is more than a year old now, so it would be great to have confirmation this before wasting time trying it out. @proppy?

**Comment by adams-sarah** [comment]
I set up datastore emulator (following instructions here https://cloud.google.com/datastore/docs/tools/datastore-emulator).
Started emulator with:
```
$ gcloud beta emulators datastore start --no-legacy
```

Set the following environment variables (exactly as documented):

```bash
$ export DATASTORE_DATASET=my-project-id
$ export DATASTORE_EMULATOR_HOST_PATH=localhost:8128/datastore
$ export DATASTORE_HOST=http://localhost:8128
$ export DATASTORE_EMULATOR_HOST=localhost:8128
$ export DATASTORE_PROJECT_ID=my-project-id
```

My sample code hits the emulator and works exactly as expected.

Sample code:

```go
package main

import (
	"fmt"
	"log"

	"cloud.google.com/go/datastore"
	"golang.org/x/net/context"
)

type Person struct {
	Name     string
	Engineer bool
}

func main() {
	ctx := context.Background()

	client, err := datastore.NewClient(ctx, "my-project-id")
	if err != nil {
		log.Fatalf("failed to make client: %s", err)
	}

	anne := Person{
		Name:     "Annie",
		Engineer: true,
	}

	key := datastore.NewKey(ctx, "Person", "", 5662329727352832, nil)
	if _, err := client.Put(ctx, key, &anne); err != nil {
		log.Fatalf("failed to put: %s", err)
	}

	anne = Person{}
	if err = client.Get(ctx, key, &anne); err != nil {
		log.Fatalf("failed to get: %s", err)
	}

	fmt.Printf("%#v\n", anne)
}
```

Output:
```
$ go run datastore.go
main.Person{Name:"Annie", Engineer:true}
```

Corresponding emulator log:
```
[datastore] INFO: Adding handler(s) to newly registered Channel.
[datastore] Sep 12, 2016 2:46:28 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
[datastore] INFO: Detected HTTP/2 connection.
[datastore] Sep 12, 2016 2:46:47 PM com.google.appengine.api.datastore.dev.LocalDatastoreService$11 run
[datastore] INFO: Time to persist datastore: 1 ms
```

Am I missing something?
What needs to be documented?

**Comment by rakyll** [comment]
I guess the expectation is that the client should run against the devappserver (at localhost:8080), the developers simply don't know they need to run the emulator to use this client.

Can we document how to start the emulator in the datastore godoc somewhere or just give a link to https://cloud.google.com/datastore/docs/tools/datastore-emulator?

I think once the emulator is out of beta, this will be more seamless. But for now, docs would be good to have.

**Comment by adams-sarah** [comment]
Got it! Ok, will do.

**Comment by adams-sarah** [comment]
It looks as though we are using @okdave 's personal github key for interactions between Gerrit and Github. Can we create a bot user for this instead? Esp. considering that Dave will be moving teams at some point.

/cc @broady @rakyll @jba @zombiezen

**Comment by broady** [comment]
Filed #369

**Comment by cyxg** [comment]
Sorry for 'abusing' this thread, but I'd like to ask @adams-sarah: the reason you manually set the key in `datastore.NewKey(ctx, "Person", "", 5662329727352832, nil)` is because the emulator cannot automatically generate a key?

When I try to run `datastore.NewKey(ctx, "Person", "", 0, nil)` or `datastore.NewIncompleteKey(ctx, "Person", nil)` then I get the error: `failed to get: rpc error: code = 3 desc = Key path element must not be incomplete: [Person: ]`

**Comment by adams-sarah** [comment]
@cyxg for a Key to be valid, it must have either a name or an ID. So when Put-ing a new entity, you may want to do something like:
```
key := datastore.NewKey(ctx, "Person", "Annie", 0, nil)
```

See godoc here for more examples and documentation: https://godoc.org/cloud.google.com/go/datastore

**Comment by adams-sarah** [comment]
I apologize, I think this may actually be a bug. 
Made an issue you can track: https://github.com/GoogleCloudPlatform/google-cloud-go/issues/411
I'll work on this tomorrow.

**Comment by adams-sarah** [comment]
@cyxg ok major blunders here on my part. My apologies, I am fairly new to this project.
You can 100% Put with an incomplete key, i misspoke. The issue with the above code is on the Get.
`client.Put` returns both a complete key and an error. In my example code above, I ignore the new key.

The Put code should read:
```
key := datastore.NewKey(ctx, "Person", "", 5662329727352832, nil)
key, err = client.Put(ctx, key, &anne)
if err != nil {
    log.Fatalf("failed to put: %s", err)
}

// and then use the updated Key (which now has an ID) in the Get, not the old incomplete key.
```

So sorry about the confusion. Please let me know if you run into any other issues.

**Comment by cyxg** [comment]
Hi @adams-sarah, thanks a lot for the response (and sorry for my slow response) :)!

Upon further digging I also saw that the code did successfully Put with NewIncompleteKey using your code, but I became (and still am) super confused when the keys generated end up being incrementing digits since I could've sworn it was supposed to be a very long randomly generated number.. I can also see it's documented (https://cloud.google.com/appengine/docs/go/datastore/entities) that default policy should generate a number with 16 random digits, whereas the legacy policy should generate in the way I experience it now.. but what confuses me is the fact that I start the emulator using `--no-legacy` flag (`gcloud beta emulators datastore start --no-legacy`), yet all the ID's generated appear to be using the legacy policy..

Anyway, it's not the end of the world since it's working, I just find it rather confusing :)
