### ISSUE TITLE
ApplicationDefaultCredentials don't work in the Cloud Shell

### ISSUE THREAD

**Issue by hjfreyer** [GoogleCloudPlatform/google-cloud-go#288]
After some digging, I found the reason: The go implementation looks for default credentials provided by the SDK only in $HOME/.config/gcloud. However, on the cloud shell, that's not where the configuration is stored. It's stored under /tmp/, and pointed to by $CLOUDSDK_CONFIG, which go doesn't check.

See the python implementation for a comparison: https://github.com/google/oauth2client/blob/master/oauth2client/client.py#L1483

Workaround is to run:

export GOOGLE_APPLICATION_CREDENTIALS=$CLOUDSDK_CONFIG/application_default_credentials.json

**Comment by bradfitz** [comment]
CLOUDSDK_CONFIG was never mentioned in the specification of Application Default Credentials we were given to implement.

How is it defined?

Is it part of Application Default Credentials, or something gcloud-specific?

Maybe Cloud Shell should be setting $GOOGLE_APPLICATION_CREDENTIALS instead of (or in addition to) $CLOUDSDK_CONFIG.

I'd like to understand the answers to this before we make changes to the Go package.

/cc @okdave @mcgreevy

**Comment by okdave** [comment]
I'm following up with the cloud shell folk to see what we can do. I agree, I don't want to rush into changing the Go package.

**Comment by okdave** [comment]
@hjfreyer do you mind sharing exactly what you're doing? In my local experiments, `google.DefaultTokenSource` is working as expected. The configuration is not available in `.config/gcloud` as you said but, since this is running on a GCE instance, it is available from the metadata service.

You can check this manually by calling the metadata service directly (or by trying to call `google.ComputeTokenSource` directly):

    $ curl 'http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token'

**Comment by hjfreyer** [comment]
This is on the Google Cloud Shell I'm talking about. This guy:
https://cloud.google.com/shell/docs/

**Comment by okdave** [comment]
What code are you trying to run? How does it fail? A local test for me (along these lines, please excuse typos), works as expected:

    ctx := context.Background()
    ts, err := google.DefaultTokenSource(ctx, "foobar")
    if err != nil { // handle err }
    fmt.Println(ts.Token())

**Comment by hjfreyer** [comment]
It's not that it fails, it's that if you've changed the default application
credentials account with gcloud, it will ignore them and use your account.

Repro instructions:
https://gist.github.com/anonymous/46af4c941d856aaf8ffc831fd676c3ee

**Comment by broady** [comment]
I was about to agree with @bradfitz about there being no mention of `CLOUDSDK_CONFIG` environment variable, but the ADC spec is a bit hazy. It says:

> If you have installed the Google Cloud SDK on your machine and have run the command gcloud beta auth application-default login, your identity can be used as a proxy to test code calling APIs from that machine.

That isn't well specified. I suppose we need to keep up with whatever changes the Cloud SDK makes. It would be nice if it wasn't a moving target.

To move forward, I'd suggest one of the following needs to happen:
- Add `CLOUDSDK_CONFIG` to the ADC spec (then we update the Go package).
- Make Cloud Shell set the `GOOGLE_APPLICATION_CREDENTIALS` env var.
- Make Cloud Shell use `$HOME` for config (i.e., unset `CLOUDSDK_CONFIG`)
- Update the ADC spec to be more specific about how the `gcloud auth login` integration works (and have Cloud SDK commit to it).

**Comment by aalexand** [comment]
I think Cloud SDK and all ADC implementations just need to agree about the location of the ADC file when CLOUDSDK_CONFIG is set.  It looks like the Python implementation does respect the variable, https://github.com/google/oauth2client/blob/master/oauth2client/client.py#L1483.

Unsetting CLOUDSDK_CONFIG in Cloud Shell would have some side effects which I am not too happy about - it currently gives separate configuration location to each tab to isolate them.  We had other complaints when it was not the case.

**Comment by broady** [comment]
Resolved: we decided not to honor CLOUDSDK_CONFIG, in the interest of maintaining simplicity for the ADC spec.
