### ISSUE TITLE
bigquery: use "Update" instead of "Patch"

### ISSUE THREAD

**Issue by jba** [GoogleCloudPlatform/google-cloud-go#325]
Use the more accepted term "Update" for updating TableMetadata.

**Comment by jba** [comment]
@mcgreevy Are you OK with this?

**Comment by mcgreevy** [comment]
LGTM.

Usually patch implies that it is possible to modify specific fields, whereas an update requires sending the entire resource.  However, since we're not providing a REST API here, I guess we don't need to stick with that convention, especially since the documentation makes it clear how this works.

**Comment by schmohlio** [comment]
Hi all. 

Thanks again for this beautiful gcloud library. Curious if there is any ETA for a `func (*TableMetadataPatch) Schema` operation, or some other way to programmatically patch/update schemas for tables. I saw it annotated. Really appreciate it.  

PS we specialize in moving customers onto bigquery/gcloud from other data warehouses by making it easy to ingest data :)

**Comment by jba** [comment]
Added #370 for patching a schema.

**Comment by jba** [comment]
Added Table.Update in 2096d282df0cbfc9d56742b68f70b737db3a882b.
