### ISSUE TITLE
bigquery: Include way to get Statistics.Query from job when running copy (mainly to get TotalBytesBilled)

### ISSUE THREAD

**Issue by segfault88** [GoogleCloudPlatform/google-cloud-go#347]
I need to get (at least) TotalBytesBilled from running queries, and I'd like to use this library other than this issue...

I'm open to working on this issue, would it be worthwhile/probably accepted?

At the moment as far as I can tell, I would need to:

Add a function to the bigqueryService very similar to [jobStatus found here](https://github.com/GoogleCloudPlatform/gcloud-golang/blob/master/bigquery/service.go#L299) (maybe jobQueryStatus?) that includes the "statistics.Query" field(s).

Add a function on the Job struct to call this new function (maybe called QueryStatus?).

Add a new struct to return and include a few fields like:
- BillingTier
- CacheHit
- TotalBytesBilled
- TotalBytesProcessed

I really like this library otherwise. Thanks!

**Comment by segfault88** [comment]
Alternatively, I could add something to return the Client's service to make doing custom things outside what this library supports much easier (rather than essentially copy and pasting the NewClient function to my own code). This would be a simpler change and would allow much more "custom" actions.

**Comment by mcgreevy** [comment]
Yes, this would be worthwhile and would be gladly accepted.

A couple of things other things to be aware of before you start work:

- You'll need to accept the contributor license agreement (see 
https://github.com/GoogleCloudPlatform/gcloud-golang/blob/master/CONTRIBUTING.md )
- We use gerrit for code review (all code committed to the repo first goes through a code review process).  Again, see CONTRIBUTING.md
- Please add tests for your code.  For unit tests you can construct a Client with a fake implementation of the service interface.  Your unit tests will end up being pretty minimal.  More importantly, please add an integration test to integration_test.go.

Re: your proposed steps:

-  yes, you should add something like `jobStatus` to the `service` interface (I'd call it `jobStatistics`; it shouldn't be limited only to query stats).
- yes, you should add a method on `Job`, but it should look like:

`func (j *Job) Statistics(ctx context.Context) (*JobStatistics, error)`

the `JobStatistics` struct should look like:

```
type JobStatistics struct {
  Creation time.Time
  Start time.Time
  End time.Time
  Details StatisticDetails
}

type StatisticDetails interface {
  implementsStatDetails() // dummy method implemented by each detail struct.
}
```

Then you'll have three structs which implement StatisticDetails and store the details for each operation:

```
type ExtractStatistics struct {
   DestinationUriFileCounts int
}
func (s ExtractStatistics) implementsStatDetails() {}

type QueryStatistics struct {
  BillingTier int
  CacheHit bool
  TotalBytesBilled int
  TotalBytesProcessed int
}
func (s QueryStatistics) implementsStatDetails() {}

// similarly for LoadStatistics, which also has only 4 fields.
```

Rather than having a separate method (e.g. QueryStatus) for each type of Job, this allows users to lean on the language a bit more using type assertions or type switches.  Users who are expecting query stats can do:

```
stats, err := job.Statistics(ctx)
// TODO: handle err
bytesBilled := stats.Details.(bigquery.QueryStatistics).TotalBytesBilled
```

Users who don't know what kind of job they're dealing with can do:
```
stats, err := job.Statistics(ctx)
// TODO: handle err
switch d := stats.Details.(type) {
bigquery.QueryStatistics:
    fmt.Printf("billed: %v", d.TotalBytesBilled)
bigquery.LoadStatistics:
    fmt.Printf("input files: %v", d.InputFiles)
// etc
}
```

Note: I'm not sure how useful it would be to write the switch above, but the point is that storing the operation-specific details in a `StatisticDetails` interface gives people greater flexibility than a set of methods on `Job` (such as `QueryStats`, `ExtractStats`).

**Comment by segfault88** [comment]
Awesome, thanks for all the details! I'll get working on this soon.

**Comment by c0b** [comment]
@segfault88 how is the progress now? Could you generalize it because other types of job also possibly carry a `statistics`; e.g. after every loading job done, I would like to know the loading job statistics; this following is what I get from `bq` tool of google-cloud-sdk; from the [Bigquery API Reference v2](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs#configuration.load) there are `load`, `query`, `copy`, `extract` different types

```json
 "status": {
  "state": "DONE"
 },
 "statistics": {
  "creationTime": "1488928593551",
  "startTime": "1488928593792",
  "endTime": "1488928846492",
  "load": {
   "inputFiles": "1",
   "inputFileBytes": "56158058",
   "outputRows": "425640",
   "outputBytes": "262669960"
  }
```

**Comment by c0b** [comment]
@mcgreevy does your tentative code include `statistics.query.queryPlan` as well? how about just expose the rest api response? #554 to be more generic and future-proof?

**Comment by c0b** [comment]
the actual question to @jba from #554 is: when you're picking up this work, would you also make sure `statistics.query.queryPlan` is included as well?

from example in https://github.com/GoogleCloudPlatform/google-cloud-go/issues/554#issue-213556319

**Comment by c0b** [comment]
@jba any reason #347 #110 #108 can't get progress faster?

**Comment by jba** [comment]
I'll try to get to (some of) them next week.

**Comment by jba** [comment]
Implemented in https://code-review.googlesource.com/c/11713.
