### ISSUE TITLE
storage: reconsider location of Object methods

### ISSUE THREAD

**Issue by okdave** [GoogleCloudPlatform/google-cloud-go#350]
The `ObjectHandle` has a few methods which seem inconsistent, and might deserve to be moved to other parts of the API hierarchy. Eliding details, these methods are:

- `dest.NewWriter(attrs)`
- `dest.NewReader()`
- `src.CopyTo(dest)`
- `dest.ComposeFrom(srcs, attrs)`

Ideas:

- move the "object creation" methods to a higher-level (`BucketHandle` or `Client`):
   - eg. `bucket.NewWriter(destName, attrs)`
   - or `client.NewWriter(destBucket, destObj, attrs)`
- change `CopyTo` to `CopyFrom` (since we can't invert compose)
   - `dest.CopyFrom(src)`
- move just the copy/compose functions to client:
   - `client.Copy(dst, src)`
   - `client.Compose(dst, srcs)`
- do nothing

/cc @rakyll @mcgreevy @jba

**Comment by jgraettinger** [comment]
Hi! As a _user_ of the `storage` package: what's the road-map towards a stable API, and can questions like this be considered in that context? We make heavy use of this among other cloud packages, and it's had a fair amount of churn in the last year. Each has been individually reasonable, but it's of course still a chore to update a significant code base.

The issue is compounded by the coupling of Go packages for different Cloud Platform APIs / GRPC / google.golang.org/api etc, which means its tough to update any one API without also updating the rest of the world. Thanks

**Comment by jba** [comment]
@jgraettinger, good question.

We're hoping to resolve these larger, breaking changes soon—within the next month. When we make the next set of breaking changes, we'll try to do it in a single commit and announce it on [google-api-go-announce](https://groups.google.com/forum/#!forum/google-api-go-announce). Around that time we'll declare these libraries "beta," which indicates that we're closer to stability. We don't expect major breaking changes after that, but we will continue to refine the API based on user feedback.

At a later time, when we mark these libraries as "stable," you can be assured of at least one year from the time we deprecate a feature until its removal. 

We'll also be using semver-compatible tags on the repo to aid in vendoring.

**Comment by okdave** [comment]
For the record, of the 4 options I listed above, I am opposed to the first. I am most in favour of (3) and (4) – move `Copy` and `Compose` to the client, or do nothing.

**Comment by jba** [comment]
There are three ways to create or modify an object's contents: writing, copying and composing. They should all look the same.

REST guidelines, to which contemporary Google APIs conform, dictate that creation methods should be on the parent resource. But since all of these operations can modify an existing object, they actually match the REST update (PUT) method, which operates on the resource itself. (I don't think we should put a lot of weight on REST in designing our clients, but in the absence of other criteria it's a reasonable data point.)

Therefore:

  obj.NewWriter
  obj.CopyFrom
  obj.ComposeFrom

which is what we have except for reversing Copy.

Some related issues:

1. All these methods let you set new metadata (ObjectAttrs) on the destination object. ComposeFrom and the proposed CopyFrom method put these at the end, far from the destination object, and that action at a distance is a bit spooky:

   dst.ComposeFrom(ctx, sourceObjs, dstAttrs)

NewWriter does it differently: you set the desired attributes individually on the returned writer:

   w := dst.NewWriter(ctx)
   w.ContentType = "text/html"

I propose we unify these with each other and with the condition mechanism:

  dst.WithAttrs(&ObjectAttrs{...}).Whatever(...)

WithAttrs has the same issue as WithConditions, so if you're okay with the latter you should be okay with the former. The issue is that the resulting ObjectHandle has state which is probably only intended for the next operation. An additional problem with WithAttrs is that it only makes sense on a destination object. We can check for common misuses at runtime.

2. If we adopt WithAttrs, we could unify CopyFrom and ComposeFrom into

  ObjectHandle.CopyFrom(sources ...ObjectHandle)

Is this a good idea? Compose differs from Copy mostly in that its source objects must be in the same bucket as the destination object. Is this worth a separate method?

3. Creating a bucket is a straightforward RESTful Create operation. For consistency with REST, I think we should have Client.CreateBucket instead of Bucket.Create.

**Comment by jba** [comment]
Users, we'd love your feedback:

We're trying the idea of putting Copy and Compose on the Writer. You can read the [CL](https://code-review.googlesource.com/#/c/7655) or check out the godoc for [NewWriter](https://godoc.org/github.com/jba/google-cloud-go/storage#ObjectHandle.NewWriter) and the [Writer methods](https://godoc.org/github.com/jba/google-cloud-go/storage#Writer).

Pros:
- All content-modifying operations are in one place.
- Setting and getting metadata doesn't get in the way.

Cons:
- Writer has two mutually exclusive modes, which may be confusing.

**Comment by jba** [comment]
Based on negative comments on the above CL, I've moved copying to a separate object. See the [CL](https://code-review.googlesource.com/#/c/7697) or check out the [godoc](https://godoc.org/github.com/jba/google-cloud-go/storage#Copier).

**Comment by jba** [comment]
@jgraettinger, have you seen https://groups.google.com/d/topic/google-api-go-announce/5nsWL8RmVqI/discussion? We'll be making these changes within a week.

**Comment by jba** [comment]
The changes are in.
