### ISSUE TITLE
storage: invalid MediaLink when object name contains slash

### ISSUE THREAD

**Issue by dsoprea** [GoogleCloudPlatform/google-cloud-go#354]
### Symptoms

Works:

Image uploaded as object with filename "local-image-U:0c260b9a73607fcd9497-I:2c8714d8b0fef898b5b8?generation=1473535857242926" returns URL "https://www.googleapis.com/download/storage/v1/b/project-id.appspot.com/o/local-image-U:0c260b9a73607fcd9497-I:2c8714d8b0fef898b5b8?generation=1473535857242926" in the *MediaLink* field.

Doesn't work:

Image uploaded as object with filename "staging/local-image-U:0c260b9a73607fcd9497-I:826f8274afba68b22c7e" will write the file into the "staging" folder as expected, though the URL in MediaLink will be invalid in a couple of different ways:

1. The slash will be URL-encoded somewhere in the pipeline and the percent symbol totally screws up the URL assembly (wherever that is): https://www.googleapis.com/download/storage/v1/b/project-id.appspot.com/o/staging%!F(MISSING)local-image-U:0c260b9a73607fcd9497-I:826f8274afba68b22c7e?generation=1473536204658886&alt=media
2. Even if you fix this by hand to become similar to what we got in the working example above, it still won't work. The only difference between the two examples is the folder-prefix. If you go to the storage console, the public URL that you get there works fine.

The [source](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/storage/storage.go#L775) seems to indicate that this URL comes directly from Google. **I tried doing a second attributes request and get the same URL back.

### URL Structure

Also, the URL set in *MediaLink* is not at all similar to what you get for the public-URL from the storage console (the webpage).

From the API:

https://www.googleapis.com/download/storage/v1/b/project-id.appspot.com/o/local-image-U0c260b9a73607fcd9497-I2c8714d8b0fef898b5b8?generation=1473535857242926&alt=media

From the storage console:

https://storage.googleapis.com/project-id.appspot.com/local-image-U0c260b9a73607fcd9497-I2c8714d8b0fef898b5b8

The API link not only seems to show some "signed" behavior (you can't strip the query arguments without invalidating the link, which is odd because there's no token in it), but it has a "Content-Disposition: attachment" response header attached to it, so it'll also want to download rather than display in a browser window (a minor point).

### Objective

I'd like to simply upload a file into a bucket folder and get back a simple URL like the one you get from the storage console. Am I not doing it the right way? Until there's a fix for this, I'm having to do a concatenation, which is obviously dangerous. Something like this:

```go
url := "https://storage.googleapis.com/" + project_id + "/" + remoteFilepath
```

Thanks.

**Comment by okdave** [comment]
@dsoprea the URL structure part should form its own feature request; it's unrelated to the first part. I don't think that returning the different URL is a bug – all we're doing is forwarding the `MediaLink` back from the server (modulo the bug that you've highlighted in the first part). The UI/console is simply returning the [XML request URI](https://cloud.google.com/storage/docs/xml-api/reference-uris) for the object – which should be equally safe for you to construct as long as you follow the correct escaping.

**Comment by okdave** [comment]
@dsoprea I can't reproduce the error you're seeing. In the [storage integration test](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/storage/integration_test.go#L181) we create an object named `obj/with/slashes`. Calling `Attrs` on this object gives me the following URL:

https://www.googleapis.com/download/storage/v1/b/dulcet-port-762-go-cloud-storage-test-1473649310339221634/o/obj%2Fwith%2Fslashes?generation=1473649315176000&alt=media

You can see that it has been correctly escaped, and it works as expected (it will 404 now though, since the integration test always cleans up after itself).

Can you check if there are any stray places you might be calling `fmt.Sprintf` on the URL before using it?  If the URL is being formatted, the `fmt` package will see `%2F` and try to interpret it as a float (hence the `%!F(missing)` error string). Otherwise, would you mind sharing a minimal working example which demonstrates the problem you're seeing?

Thanks. I'll close for now, but please re-open if you're still seeing the issue.

**Comment by dsoprea** [comment]
@okdave I'll assume that your comments are totally related to the "URL Structure" portion, right? Obviously the URL coming back is totally broken right now (due to the "%!F(MISSING)").

**Comment by dsoprea** [comment]
@okdave Ok, Dave. I'll re-run it in the near future. Can't do it right now.
