### ISSUE TITLE
datastore tx.Put throws "error while saving"

### ISSUE THREAD

**Issue by schmohlio** [GoogleCloudPlatform/google-cloud-go#364]
Hi all,

I'm trying to catch `ErrINvalidEntityType` errors when calling `tx.Put(key, entity)` and instead receiving `datastore: Error while saving /{kind},{keyname}: datastore: invalid entity type`. Is there a better way to catch these errors than parsing text? is there some type to cast errors from transactions?

Thanks in advance.

**Comment by schmohlio** [comment]
or for that matter, is there some blanket logic for delineating between IO errors in the event that datastore is unavailable vs application errors?

**Comment by okdave** [comment]
Thanks. We definitely should be returning `ErrInvalidEntityType` – I'll fix that.

Unfortunately, at the moment there's no consistent way to distinguish between IO errors or application errors (or, for that matter, backend failures). This is complex to do in general: we can't completely check for application logic errors on the client side since the server itself does some correctness checks on the entities you try to store/the requests you make. One example is that only the server knows which indexes have been defined, and therefore which queries are valid. We do need to do a better job of classifying these errors though so we can allow some programmatic detection between them. That's out of scope for this bug though.

**Comment by schmohlio** [comment]
makes sense @okdave . Appreciate the response.
