### ISSUE TITLE
storage: remove (*Client).Close

### ISSUE THREAD

**Issue by rakyll** [GoogleCloudPlatform/google-cloud-go#366]
Close is doing nothing in terms of freeing anything or cleaning a buffer. Therefore, it is not necessary to close the storage clients. See yourself at https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/storage/storage.go#L146

On the top of that, current Close method returns and error and documented as a necessary call which makes it harder to use the storage client and handle its life cycle.

We should remove the closer from this package.

/cc @jba @okdave @broady

**Comment by okdave** [comment]
It's there to support a future upgrade to gRPC without breaking any of the API surface.

**Comment by bradfitz** [comment]
Both the JSON API and gRPC API have an optimization of keeping a cached TCP connection open for reuse.

The JSON (HTTP) API does it via net/http.Transport, where it eventually times out due to lack of use.

Why can't gRPC just shut down its cached TCP connection after _N_ seconds of idle? Maybe it already does.

I guess my question is: why does gRPC require a different API from another thing which is also just HTTP requests under the covers?

**Comment by jba** [comment]
To answer your last question first, I naively assume that all HTTP is connection-per-request. Obviously that is not the case.

But even with close-on-idle, couldn't you still get into trouble if you don't have control over shutting down the connection? What if you have some sort of proxy and you need a separate backend client per frontend connection, for auth perhaps. Couldn't you run out of descriptors at peak?

**Comment by jba** [comment]
Let's resolve this by end of week. 

I'd like a single answer for all clients, for consistency. Do we agree on that? 

My feeling now: in my current state of knowledge, I don't know whether Close is important on this client or any other in this repo, except that the new logging client uses it to make sure async operations have finished.

None of us know if any of the clients will later need Close. They may want to shut down goroutines, or close connections using transports that don't support close-on-idle, or depend on other services that require Close for their own reasons. And I still am not convinced that close-on-idle will free resources fast enough in some cases, as I wrote above. 

This is a case where we can't just add it later: it is backwards-incompatible to require calling Close when we hadn't before. Conversely, having Close now means we can remove it later, or make it a no-op, without changing behavior.

I don't think Close adds much to the complexity of using a service. Typically you'll use a client in the lifetime of one method (possibly main), in which case you just write a defer. Many other cases, like lazy creation, can be handled by `defer func() { if client != nil { client.Close() }}` in main, assuming the client is in a global. @rakyll, can you give examples where it's harder than that to deal with Close?

So I vote for adding Close to all clients.

Interested in your thoughts, @bradfitz @rsc @robpike.

**Comment by bradfitz** [comment]
> And I still am not convinced that close-on-idle will free resources fast enough in some cases, as I wrote above.

It's not like every operation has some lingering resources associated with it. There should be exactly 1 cached & idle-for-a-bit TCP connection open for the entire program. And with HTTP/2, there should really just be one for all Google APIs, regardless of hostname (storage.googleapis.com and foo.googleapis.com sharing the same conn), since requests can be coallesced based on the hostnames listed in the TLS cert.

And I don't think any of our existing `Close` methods in any API library call through to see if the user's provided `*http.Client`'s `Transport` supports a `CloseIdleConnections` method. Even if it did, I don't think you'd want to call it, since it would close all idle connections for all hosts, even non-Google API hosts.

Likewise, gRPC doesn't technically need shutdown. (Although the current implementation might a bit, but shouldn't.)

> None of us know if any of the clients will later need Close. They may want to shut down goroutines, 

Both flushing and closing down goroutines are a more valid reason.

> So I vote for adding Close to all clients.

That's fine.

But please document the expected lifetime and concurrency-safety of the clients enough so people aren't creating & closing them a bunch.

The Close docs should de-emphasize their importance somehow.

**Comment by jba** [comment]
> But please document the expected lifetime and concurrency-safety of the clients enough so people aren't creating & closing them a bunch.

Not sure what you mean by "expected lifetime". By concurrency-safety I assume you mean whether it's safe to have multiple concurrent calls to Close?

I also don't understand why "creating & closing them a bunch" is a bad thing, or why anything we say about Close would make people do it. Do you mean that for simplicity someone will create all their clients in main, so they can defer Close there as well?

Probably the most common case is that you create a client, eagerly or as needed, and then just leave it open for the life of the program. I'm fine saying something like "If the program terminates without Close having been called, no big deal" on most clients, logging being the big exception.

**Comment by bradfitz** [comment]
I mean something like the docs at the bottom of Transport: https://golang.org/pkg/net/http/#Transport

If the object is heavy and will have associated TCP connections, it should be reused for a long time from multiple goroutines, and not created and closed repeatedly deep inside some call stack.

Doing a defer to close it in main is useless. Your program can just exit and tear it down. ("Crash-only software", etc.)

Just let people know what to expect and how heavy (or not heavy) each client is.

**Comment by broady** [comment]
Another use case to consider is on App Engine, where currently a new client must be opened for each incoming request.

The urlfetch client doesn't keep any resources around, though, so maybe it's not much of a consideration.

**Comment by okdave** [comment]
I do believe that the AE folk are hoping to get to the point where we don't need a new client on each request. I wonder if we could do something intelligent today on AE to allow a long-lived client (already, each request takes a `ctx` – so we might be able to fake a long-lived client that did a dial-per-func underneath today?)

@bradfitz re the single connection for all APIs – do we need to do something here to make sure that happens, or is that plumbing happening under the hood already?

**Comment by rakyll** [comment]
> can you give examples where it's harder than that to deal with Close?

It is confusing. I have a crash-only program, I want to crash if any error happens and I am not sure how critical is to close the client. I jump to the definition and see what Close is doing nothing. As a developer, I learn that I shouldn't care about closing the storage client given it does nothing. Putting a Close method is not going to make people call it unless it is not doing anything it says.

Just two cents.

**Comment by jba** [comment]
> I want to crash if any error happens and I am not sure how critical is to close the client

The Close doc will make it clear that you don't have to close at exit.

**Comment by jba** [comment]
> I want to crash if any error happens and I am not sure how critical is to close the client.

I'll make it clear that you don't have to call Close on exit.
