### ISSUE TITLE
storage: cannot delete fields using Update

### ISSUE THREAD

**Issue by zombiezen** [GoogleCloudPlatform/google-cloud-go#380]
The [patch semantics](https://cloud.google.com/storage/docs/json_api/v1/how-tos/performance#patch) say that you can delete fields:

> Delete: To delete a field, specify the field and set it to null. For example, "comment": null. You can also delete an entire object (if it is mutable) by setting it to null.

However, you cannot express this using either the generated API or the storage package.

/cc @jba @adams-sarah

**Comment by jba** [comment]
The generated client (at google.golang.org/api/storage/v1) does support the PATCH method, and does have the ability to send empty fields, via ForceSendFields.

However, encoding/json will encode an empty string as `""` and an empty map as `{}`. The only values it encodes as `null` are nil slices, nil pointers, and nil interface values. 

Even if this worked, the storage package doesn't use it. Filing a separate bug there.

**Comment by jba** [comment]
All the possibilities for updating the metadata map, determined experimentally:

Request Body | Patch | Update
--- | --- | ----
`{}` | nop | clear
`{"metadata":{}} ` | nop | clear
`{"metadata":null} ` | clear | clear

No surprises here, just writing it all down in one place.

**Comment by jba** [comment]
More about patching metadata: if you provide a map, it is merged with the existing one; it does not replace it. In other words, any new keys are added to the existing map, and no existing keys are removed. This matches the sentence on the Patch Semantics page that says "The modified data you send is merged into the data for the parent object, if there is one." In that sentence, "object" means JSON object, not GCS object.

Since the high-level client (cloud.google.com/go/storage) implements ObjectHandle.Update using Patch, that means there is currently no way to remove keys from the metadata, and even when Patch is fixed to allow deletion, the only way to remove a key will be to make two RPCs, one to delete the metadata and one to replace it.

**Comment by jba** [comment]
Proposal for cloud.google.com/go/storage: ObjectHandle.Update would take 

```
type ObjectAttrsUpdate {
    ObjectAttrs
    DeleteContentType bool
    DeleteContentLanguage bool
    DeleteMetadata bool 
    ...
}
```
We could construct the appropriate PATCH request from that, assuming the low-level package is fixed.

It's much harder to handle removing keys from the metadata in one RPC, fundamentally because doing an update requires passing the ACLs, and getting the ACLs from an ObjectHandle might itself require an RPC. So there is no worthwhile fix; the user must delete and re-construct the metadata map in two calls. If there is a strong need for a convenient way to do this, we can provide it, but it won't be efficient.

Thoughts, @okdave @bradfitz @broady?

**Comment by bradfitz** [comment]
I don't even think any of those 3 are ever really needed, and where do we stop adding "DeleteFoo" bools? There are surely tons more of them.

I'd prefer something even more inconvenient if it solves the whole problem and gets out of the way in the docs.

But if those are the only 3... I suppose that's okay.

**Comment by jba** [comment]
This is everything in ObjectAttrs that is not marked read-only:

ContentType
ContentLanguage
CacheControl
ACL
ContentEncoding
ContentDisposition
Metadata

Would you prefer something like

DeleteFields []string // names of fields to delete?

or do you have something even more inconvenient in mind?

**Comment by bradfitz** [comment]
The variadic `deleteFields ...string` is a little weird, but `DeleteFields []string` seems intriguing. Maybe with a type and some package-level consts, for type happiness?

```go
// Field is the name of Cloud Storage metadata field. Currently these are only
// used for deleting things.
// NOTE(bradfitz): does this show up anywhere else? Listing which fields you're patching or GETing?
type Field string

const (
    FieldContentType Field ="Content-Type"
    // ...
)

type ObjectAttrs struct {
// ...
     Delete []Field
// ...
}
```

**Comment by jba** [comment]
How does the list of constants give you less doc clutter than the list of fields?

I'm okay adding non-attribute fields to ObjectAttrs if that's the best way, but here we could easily have another type that embeds ObjectAttrs and adds the delete field.

**Comment by adams-sarah** [comment]
Forgive me for being naive, but could we not just have a separate method for deleting metadata by key, instead of cluttering up the Update? I realize that currently PATCH corresponds to Update 1:1, but we could theoretically have two methods in the client which correspond to PATCH, Update and maybe, RemoveMetadata? Where RemoveMetadata could take a list of keys to remove ?

```
func (o ObjectHandle) RemoveMetadata(fields ...string)
// or
func (o ObjectHandle) RemoveMetadata(fields []Field)
// ...or...
```

**Comment by rakyll** [comment]
What about having not overdoing this and just having an Update working like PUT and introducing a Patch that works like PATCH?

**Comment by jba** [comment]
> a separate method for deleting metadata

Metadata is just one example.  There are about 7 fields.

**Comment by jba** [comment]
> What about having not overdoing this and just having an Update working like PUT and introducing a Patch that works like PATCH?

The update method for objects requires an ACL, which is annoying and potentially expensive. I don't think we need it.

**Comment by jba** [comment]
A related issue: setting something to its default value. For instance, BucketAttrs now has VersioningEnabled, a bool. When we add the ability to patch a bucket, how will the user turn off versioning?

**Comment by jba** [comment]
I recommend we use the idea of [field masks](https://github.com/google/protobuf/blob/master/src/google/protobuf/field_mask.proto) to handle all these cases. That is what the new Google gRPC-based APIs will do, so it will help consistency in the future.

The update struct will have a field
```go
UpdateFields []string
```
which lists the fields to change. There is no distinction between deleting a field of primitive type and setting it to its default value, but I don't think there is anywhere in the storage API where that matters. And it can't matter in a gRPC-based API, because protobuf doesn't distinguish between a empty primitive field and a missing one.

As a convenience, the only field names that the user has to set are the ones that do not have their default value.

Examples:
```go
// Change ContentLanguage. (Same as now.)
obj.Update(ctx, ObjectAttrsUpdate{ContentLanguage: "en"})

// Delete ContentLanguage (== set it to "")
obj.Update(ctx, ObjectAttrsUpdate{UpdateFields: []string{"ContentLanguage"}})

// Change ContentLanguage and delete metadata.
obj.Update(ctx, ObjectAttrsUpdate{
    ContentLanguage: "en",
    Metadata: nil, // unnecessary, but here for clarity
    UpdateFields: []string{"Metadata"}, // no need to mention ContentLanguage
})

// Change a boolean field to false
bkt.Update(ctx, BucketAttrsUpdate{
   VersioningEnabled: false,   // unnecessary, but here for clarity
   UpdateFields: []string{"VersioningEnabled"},
})
```

**Comment by bradfitz** [comment]
> and even when Patch is fixed to allow deletion, the only way to remove a key will be to make two RPCs, one to delete the metadata and one to replace it.

I don't follow that. What does the JSON + HTTP request look like on the wire to delete fields?

Are you saying you can't delete some fields & update some other fields in the same HTTP request?

**Comment by jba** [comment]
> Are you saying you can't delete some fields & update some other fields in the same HTTP request?

You can do that with _fields_. I was talking about the _keys_ of the metadata map. Under patch semantics, new keys get merged in.

The field-mask idea won't work for deleting individual metadata keys. The fundamental problem is that the value type of the metadata map is string, so there is no way to tell whether the user wants to set the key to the empty string or delete it.

That's not a problem with the other object attributes. I don't think it matters whether ContentType is the empty string or not present. (If it does matter, then the field-mask idea is broken.)

You _can_ delete the whole metadata map, with `ObjectAttrsUpdate{Metadata: nil, UpdateFields: []string{"Metadata"}}`.You just can't delete individual keys with UpdateFields.

We could have another field in ObjectAttrsUpdate that lists the metadata keys you want to delete (assuming the PATCH verb actually does that when sent the right JSON, which I didn't check). But I don't think it's worth it.
