### ISSUE TITLE
message type "google.appengine.logging.v1.RequestLog" isn't linked in

### ISSUE THREAD

**Issue by broady** [GoogleCloudPlatform/google-cloud-go#423]
```
logging: unmarshalling proto payload: any: message type "google.appengine.logging.v1.RequestLog" isn't linked in
```

Code:
```
func main() {
	ctx := context.Background()

	lc, err := logadmin.NewClient(ctx, "cbro-scratch")
	if err != nil {
		errorf("logadmin.NewClient: %v", err)
	}

	entries := lc.Entries(ctx)
	for {
		e, err := entries.Next()
		if err != nil {
			errorf("Entries: %v", err)
		}
		log.Print(e.Payload)
	}
}
```

**Comment by broady** [comment]
cc @zombiezen

**Comment by zombiezen** [comment]
Aha, I have a fix.  Do we know what other types can occur in here?

**Comment by broady** [comment]
I'm not sure, I think they could be anything. Is there no general solution for this?

**Comment by jba** [comment]
There's a small list. See
https://github.com/googleapis/googleapis/issues/187. I did the main audit
log proto but haven't gotten around to the other ones.

On Fri, Nov 11, 2016 at 3:57 PM Chris Broadfoot <notifications@github.com>
wrote:

I'm not sure, I think they could be anything. Is there no general solution
for this?

—
You are receiving this because you were assigned.


Reply to this email directly, view it on GitHub
<https://github.com/GoogleCloudPlatform/google-cloud-go/issues/423#issuecomment-260053802>,
or mute the thread

**Comment by zombiezen** [comment]
@jba, that bug doesn't mention RequestLog, which is where this error came from.

**Comment by jba** [comment]
@pongad looks like we need to add
```
_ google.golang.org/genproto/googleapis/appengine/logging/v1
```
to the import list of logadmin.go. We already do this for audit logs so I assume there away to configure it.

**Comment by pongad** [comment]
Sorry, I don't completely understand this. Are `appengine/logging/v1` and `cloud/audit` somehow privileged that we should always include them? From the [proto doc](https://github.com/googleapis/googleapis/blob/f781f331a0d0269725d33c715e68fae9129f0214/google/logging/v2/log_entry.proto#L68) it looks like any service can define its own error type and messages of those types can be fetched. Shouldn't it be up to the user to link in these types? Otherwise, I think we'd have to make logadmin.go import every possible log types right?

**Comment by jba** [comment]
No, there's a fixed set of services that can use protos, so a fixed set of types. There is a list somewhere, but for now we can just link in this proto.

BTW, I was wrong in thinking this was an issue in generated code. It's just a one-line change to the handwritten logadmin client.

Running broady's code will only be an adequate test for you if you've written GAE logs to your project. If not, then ask broady to test for you.

**Comment by pongad** [comment]
@broady I just submitted [CL](https://code-review.googlesource.com/#/c/gocloud/+/15650/) that should fix this. Could you try again?

**Comment by jba** [comment]
Assuming this specific issue (linking in RequestLog) is fixed.

**Comment by broady** [comment]
Weird. My code doesn't print any log entries.

Does it need a filter? It shouldn't, right?

**Comment by pongad** [comment]
That's really odd. @broady do you know an easy way to give my test project an appengine log? I can try testing it on my side.
