### ISSUE TITLE
datastore.GetMulti misleading error msg - due to resource constraints

### ISSUE THREAD

**Issue by p0lyn0mial** [GoogleCloudPlatform/google-cloud-go#428]
While calling GetMulti I kept getting [“datastore: some entities temporarily unavailable”](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/datastore/datastore.go#L412) and must admit it took me almost the whole day to
nail it down. It turned out that this error was due to limits imposed by datastore. In my case it was the response limit.

Additionally the description of the [LookupResponse.Deferred](https://godoc.org/google.golang.org/genproto/googleapis/datastore/v1#LookupResponse) field was not so clear for me as well. 

Thus I would like to make the error message more descriptive e.g  “datastore: some entities temporarily unavailable. The error is most likely due to production limits imposed by datastore”.

**Comment by jba** [comment]
I'm not sure this is possible in the client&mdash;we may not have the information necessary to give a better message. @adams-sarah can you take a look?

**Comment by adams-sarah** [comment]
@p0lyn0mial FYI it turns out that datastore returns deferred keys when response payload is too large, not due to query limits or anything similar. The deferred keys are intended to be fetched again by the client in a second request. Apologies that there isn't better documentation on this.

So I've altered the client to fetch any deferred keys for you in another request and append to result set instead of erroring out. You shouldn't see this error anymore.

**Comment by p0lyn0mial** [comment]
@adams-sarah thank you very much for resolving this issue.

**Comment by adams-sarah** [comment]
My pleasure. Thanks for reporting it.
