### ISSUE TITLE
storage: retry on certain errors

### ISSUE THREAD

**Issue by jba** [GoogleCloudPlatform/google-cloud-go#435]
A long-running program that writes to GCS observed the following errors:

`http2: server sent GOAWAY and closed the connection; LastStreamID=124073, ErrCode=NO_ERROR, debug="max_age"`

`read tcp [2620:0:1003:1008:24d9:ea54:c16e:abe0]:33072->[2607:f8b0:4006:80e::200a]:443: read: connection reset by peer`

The client should retry on these errors, if feasible.

**Comment by joshk0** [comment]
How does the runWithRetry / internal.retry framework you wrote deal with this GOAWAY issue?

We saw that in our own long-running GCS writer, and after that, we found that this goroutine was permanently wedged:

```
goroutine 127156652 [select]:
google.golang.org/api/gensupport.(*ResumableUpload).Upload(0xc42315cbd0, 0x7ff2e91dd0f0, 0xc42
0014250, 0xc420b0e620, 0xdb, 0x0)
        /opt/build/src/google.golang.org/api/gensupport/resumable.go:171 +0x336
google.golang.org/api/storage/v1.(*ObjectsInsertCall).Do(0xc429d06c00, 0x0, 0x0, 0x0, 0x0, 0x0
, 0x0)
        /opt/build/src/google.golang.org/api/storage/v1/storage-gen.go:6753 +0x422
cloud.google.com/go/storage.(*Writer).open.func1.1(0x7ff2e91dd0f0, 0xc420014250)
        /opt/build/src/cloud.google.com/go/storage/writer.go:96 +0x5b
cloud.google.com/go/storage.runWithRetry(0x7ff2e91dd0f0, 0xc420014250, 0xc4221a9f30, 0x0, 0xcb8020)
        /opt/build/src/cloud.google.com/go/storage/invoke.go:28 +0x4f
cloud.google.com/go/storage.(*Writer).open.func1(0xc422112e00, 0xc429238f20, 0xc420022be0, 0xc423a22b40, 0x2, 0x2)
        /opt/build/src/cloud.google.com/go/storage/writer.go:96 +0x5cd
created by cloud.google.com/go/storage.(*Writer).open
        /opt/build/src/cloud.google.com/go/storage/writer.go:104 +0x48a
```

This wedged goroutine made `writer.Close()` hang forever on `<-donec`. It is not clear whether it's directly related to the GOAWAY, but I'm interested in learning if there is any interaction at all, since we're now having trouble reproducing the issue.

Is it possible that runWithRetry was infinitely retrying? I know it filters for certain error codes, but is there some kind of corner case that the retry causes the exact same retryable-looking error every single time?

We're scaling up our use of this code so that we hit the bug again, and will report back, but would appreciate if there's any help you can provide.

**Comment by jba** [comment]
Is anyone still seeing this problem?

**Comment by jba** [comment]
Closed due to lack of activity.
