### ISSUE TITLE
appengine: context.Context namespace ignored/not populated

### ISSUE THREAD

**Issue by isawk** [GoogleCloudPlatform/google-cloud-go#460]
Namespace aware API not picking up namespace, though appengine.Namespace(ctx,...) has been used to generate new namespace with no errors produced.

**Additional Information**
http://stackoverflow.com/questions/41061803/app-engine-go-context-context-has-no-namespace

**Example App** 
*(Can be modified to use http context from appengine environment)*

https://play.golang.org/p/tYEDG16MBl

**Comment by adams-sarah** [comment]
This is because you are using the cloud datastore package, "cloud.google.com/go/datastore" in conjunction with the appengine package "google.golang.org/appengine".

The appengine datastore package looks for namespace in the context.
The cloud datastore package looks for namespace on the Key object.

In general, you should only use one set of packages, either all "google.golang.org/appengine" packages, or all "cloud.google.com/go" packages. The two sets of packages will not necessarily work together.

So if you go with the cloud packages, your code should look something like:
```go
func main() {
	ctx := context.Background()
	projectID := ""

	client, err := datastore.NewClient(ctx, projectID)
	if err != nil {
		log.Fatalf("Failed to create client: %v", err)
	}

	key := datastore.IDKey("user", 0, nil)

	/* ***** THIS LINE BELOW SETS THE NAMESPACE ***** */
	key.Namespace = "client.example.com"
	/* ***** ********************************** ***** */

	user := User{Username: "john.doe", Password: "amstillalive", Roles: []Role{"IAM_ADMIN", "IAM_USER"}}
	// Saves the entity

	if savedKey, err := client.Put(ctx, key, &user); err != nil {
		log.Fatalf("Failed to save: %v", err)
	} // ...
// ...
}
```

**Comment by isawk** [comment]
Updating packages and testing.

Which package should be used? Assuming one will eventually replace the other. My guess is that `cloud.google.com/go` is going to superseded `google.golang.org/appengine`

**Comment by adams-sarah** [comment]
That is correct :). We are encouraging users to use cloud.google.com/go wherever possible, as google.golang.org/appengine will eventually be deprecated.

**Comment by isawk** [comment]
Awesome works
