### ISSUE TITLE
storage: Writer.Close() hangs waiting for w.donec to be closed.

### ISSUE THREAD

**Issue by epsniff** [GoogleCloudPlatform/google-cloud-go#470]
### Description:
We have a piece of code that consumes messages from a PubSub subscriptions and batches the messages up in blocks of 100MBs.  These 100MB blocks are then stored in Google Cloud Storage.  I'd estimate that we write one of these files every 1-2 seconds. 

This systems has been running on the google cloud code from June until 2 weeks ago.  Since upgrading the google cloud clients, we've gotten the following deadlock twice.   Below are the two routines and thier stacktraces.

### Debug Info:
Close() is blocked waiting for `w.donec` to be closed: https://github.com/GoogleCloudPlatform/google-cloud-go/blob/3dcec5a15fa0b38b716203ca66128237d0947a1c/storage/writer.go#L133  
```
goroutine 9336 [chan receive, 85 minutes]:
github.com/lytics/app/vendor/cloud.google.com/go/storage.(*Writer).Close(0xc44b4f0380, 0xc44b4f0380, 0x7f25a8745448)
	/home/aaron/go/src/github.com/lytics/app/vendor/cloud.google.com/go/storage/writer.go:133 +0x7e
github.com/lytics/app/src/eventstore/eventarchive.(*EventArchiver).storeWrite(0xc43638cab0, 0x0, 0x0, 0x0, 0x0)
	/home/aaron/go/src/github.com/lytics/app/src/eventstore/eventarchive/archiver.go:411 +0x6a1
github.com/lytics/app/src/eventstore/eventarchive.(*EventArchiver).flush(0xc43638cab0, 0x5ff5183, 0xc43543e9e0)
<truncated: I can add the full stack on request>

```

Where `w.donec` should have been closed : https://github.com/GoogleCloudPlatform/google-cloud-go/blob/3dcec5a15fa0b38b716203ca66128237d0947a1c/storage/writer.go#L82

```
goroutine 13467585 [select]:
github.com/lytics/app/vendor/google.golang.org/api/gensupport.(*ResumableUpload).Upload(0xc4cc4db3b0, 0x7f25b2793028, 0xc420010478, 0xc48dfa60e0, 0xdf, 0x0)
	/home/aaron/go/src/github.com/lytics/app/vendor/google.golang.org/api/gensupport/resumable.go:171 +0x336
github.com/lytics/app/vendor/google.golang.org/api/storage/v1.(*ObjectsInsertCall).Do(0xc4f2573680, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/aaron/go/src/github.com/lytics/app/vendor/google.golang.org/api/storage/v1/storage-gen.go:6758 +0x422
github.com/lytics/app/vendor/cloud.google.com/go/storage.(*Writer).open.func1.1(0x0, 0x0)
	/home/aaron/go/src/github.com/lytics/app/vendor/cloud.google.com/go/storage/writer.go:96 +0x5b
github.com/lytics/app/vendor/cloud.google.com/go/storage.runWithRetry.func1(0x7f25b2793028, 0xc420010478, 0x3876a5a6e)
	/home/aaron/go/src/github.com/lytics/app/vendor/cloud.google.com/go/storage/invoke.go:28 +0x2a
github.com/lytics/app/vendor/cloud.google.com/go/internal.retry(0x7f25b2793028, 0xc420010478, 0x3b9aca00, 0x6fc23ac00, 0x4000000000000000, 0x6fc23ac00, 0xc4a2a81e58, 0x7f25b463f170, 0x7f25b44080a0, 0x1)
	/home/aaron/go/src/github.com/lytics/app/vendor/cloud.google.com/go/internal/retry.go:39 +0x40
github.com/lytics/app/vendor/cloud.google.com/go/internal.Retry(0x7f25b2793028, 0xc420010478, 0x0, 0x0, 0x0, 0x0, 0xc4a2a81e58, 0x30, 0x0)
	/home/aaron/go/src/github.com/lytics/app/vendor/cloud.google.com/go/internal/retry.go:32 +0x82
github.com/lytics/app/vendor/cloud.google.com/go/storage.runWithRetry(0x7f25b2793028, 0xc420010478, 0xc4a2a81f40, 0x0, 0x7f25b4432520)
	/home/aaron/go/src/github.com/lytics/app/vendor/cloud.google.com/go/storage/invoke.go:42 +0x94
github.com/lytics/app/vendor/cloud.google.com/go/storage.(*Writer).open.func1(0xc44b4f0380, 0xc48aa2eb00, 0xc4b42e7500, 0xc461d2d320, 0x2, 0x2)
	/home/aaron/go/src/github.com/lytics/app/vendor/cloud.google.com/go/storage/writer.go:96 +0x5cd
created by github.com/lytics/app/vendor/cloud.google.com/go/storage.(*Writer).open
	/home/aaron/go/src/github.com/lytics/app/vendor/cloud.google.com/go/storage/writer.go:104  
```

Because the go routine is stuck in the [ResumeableUpload](https://github.com/google/google-api-go-client/blob/master/gensupport/resumable.go#L171) func waiting for the backoff timer or for the ctx to timeout,  I'm going to add a timeout to the context I use.    Then I'll log the context.Err() return next time I see this.   I assume we'll need to see the error returned by the server to get more insights into why it's stuck here.   

I'll add more info once I have it.  I'm not sure if this should be classified as a bug or just an FYI...

**Comment by jgraettinger** [comment]
Hi. We've hit this one too. We have also seen what I think is this bug expressed as apparently successful uploads appearing as empty in actuality, _resulting in data loss_.

I believe both are due to the same bug, introduced when [retry logic](https://github.com/GoogleCloudPlatform/google-cloud-go/commit/61a09b43cee7329f083691f0b048d7707f538191) was added to [writer.go:96](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/storage/writer.go#L96), which causes two types of failures:

1) Given large (multi-chunk) content, the wrapping MediaBuffer may be in a partially iterated state from an overall request that fails. When retried, the current MediaBuffer Chunk will be at a non-zero offset, and the resume-able upload can never complete (I believe it's infinite looping on GCS returning an error due to the missing leading content).

2) For small files of a single Chunk size (or for which chunking is disabled) a single Reader is attached to the `ObjectsInsertCall`. Once it's consumed, it's gone. That means that if the first insert attempt fails, the next retried attempt will pick up reading where it left off (typically at EOF, resulting in an empty upload).

Unfortunately retries & io.Reader (or reader-like things) don't mix :cry:

**Comment by jba** [comment]
@jgraettinger Thanks for your careful analysis. In https://code-review.googlesource.com/10331 I remove the retry.
