### ISSUE TITLE
bigtable: transport: http2Client.notifyError got notified that the client transport was broken EOF.

### ISSUE THREAD

**Issue by junghoahnsc** [GoogleCloudPlatform/google-cloud-go#480]
Hello,

I'm getting the following error sometimes:
```
transport: http2Client.notifyError got notified that the client transport was broken EOF.
```

After this error, it seems like bigtable operation doesn't work any more.
Is this error recovered automatically by bigtable client? Or should I re-open the client connection?

Thanks,

**Comment by garye** [comment]
It surprises me that the bigtable operations stop working after this message, because based on the error message I would assume you are running into #293 (#378 has a workaround). In my experience I tend to see this when my program starts by creating an AdminClient to do some admin stuff at startup but doesn't touch it again. After every 4 minutes of inactivity I see that message. 

At any rate, this error happens in the gRPC layer and should be fully handled under the covers.

Does any of this seem like what you're running into?

**Comment by junghoahnsc** [comment]
I'm using AdminClient at the beginning of the application and closing it.
I checked the Bigtable again and I noticed data is still being written even when I got the error message.
It seems like this is handled by gRPC layer.

Sorry for the spam.

**Comment by junghoahnsc** [comment]
Hello,

I got this problem again. I'm trying to copy a table. After reading/writing about 10K rows, the job was stuck  with the following error:

2017/03/30 18:44:29 transport: http2Client.notifyError got notified that the client transport was broken EOF.

It was never recovered and kept showing this error.

Thanks,

**Comment by junghoahnsc** [comment]
Sorry again,

The issue was because we write 10K+ mutations at one time, but somehow the error message was not shown.

Thanks,

**Comment by jba** [comment]
@junghoahnsc Sorry, I didn't understand your last message. Are you saying you found your problem and that it is unrelated to that log message? That message is just log spam and should not affect your application.

**Comment by junghoahnsc** [comment]
@jba, The issue was that we wrote more mutations than the limit (100k?) at a time.
But our app couldn't print that error from ApplyBulk. After reducing the number of mutation, it works. Sorry for the spam.
