### ISSUE TITLE
TimestampRangeFilter rejects time.Time objects with fractional milliseconds

### ISSUE THREAD

**Issue by atdt** [GoogleCloudPlatform/google-cloud-go#485]
`time.Time` objects need to be truncated / rounded to whole milliseconds. Consider the following filter:

```go
t := time.Now().Add(time.Duration(-5) * time.Second)
f := bigtable.TimestampRangeFilter(t, time.Time{})
```

Attempting to use this filter will typically result in the following error:

```
2017/01/11 16:56:42 Error while processing request. Closing connection. Error: rpc error: code = 3 desc = Error in field 'predicate filter' : Error in field 'timestamp_range_filter' : Timestamp granularity mismatch. Expected a multiple of 1000 (millisecond granularity), but got 1484171797214163.
```

**Comment by garye** [comment]
Good catch. The service only supports millisecond granularity but to be consistent with other API calls in the Go library we'll truncate to milliseconds and update the docs.

**Comment by atdt** [comment]
I'm not sure it is always safe to truncate. Consider the following code snippet:

```go
// `cell` is a bigtable.ReadItem obtained via an earlier call to tbl.ReadRow
newerThanCellFilter := bigtable.TimestampRangeFilter(cell.Timestamp + 1, bigtable.Timestamp(0))

// Retrieve all rows with cells that are newer than `cell`:
err := tbl.ReadRows(ctx, bigtable.SingleRow(row), func(row bigtable.Row) bool {
	// ...
}, bigtable.RowFilter(newerThanCellFilter))
```

If you truncate first argument to `TimestampRangeFilter`, the set of retrieved cells will _include_ `cell`, which is probably not what the developer expected.

There is also the issue of what to do with [TimestampRangeFilterMicros](https://godoc.org/cloud.google.com/go/bigtable#TimestampRangeFilterMicros) in a world where fractional milliseconds are truncated.

**Comment by garye** [comment]
We actually truncate timestamps for mutations as well, since the server side only supports millisecond resolution: https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/bigtable/bigtable.go#L478. The comment there is probably misleading - it's not just the "default" table config, it's all that is currently supported.

Given that, I think the `ReadRows` call you constructed would work the way you'd expect. For consistency, it seems to make the most sense to have a comment and behavior similar to the `Set` function above for timestamp filtering.

All of this exists because of a desire to match HBase's behavior so it's not ideal.
