### ISSUE TITLE
firebase client

### ISSUE THREAD

**Issue by albertog** [GoogleCloudPlatform/google-cloud-go#486]
Is there any plan to develop a official Firebase client in golang?

**Comment by broady** [comment]
No plans, but I've used this one to good effect:
https://godoc.org/github.com/zabawaba99/firego

It's nicer than some of the other ones out there, because it lets you pass in an http.Client, so you can use google.DefaultClient for authentication.

Example from App Engine standard:
https://github.com/GoogleCloudPlatform/golang-samples/blob/master/docs/appengine/firebase/tictactoe/firebase.go
