### ISSUE TITLE
all: document client connection behavior

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/google-cloud-go#516]
**EDIT**: See https://github.com/GoogleCloudPlatform/google-cloud-go/issues/516#issuecomment-324173926 for the new direction for this bug.

It looks like [datastore#Client.Close()](https://godoc.org/cloud.google.com/go/datastore#Client.Close) closes the underlying connection. However while reading the doc:

1. I see that none of the example code with `datastore.NewClient`  actually calls Close() on the client. Which makes me think maybe it

So in the godoc, I don't see any clear guidance on whether:

- the connection can be left open or should be closed.
- `datastore.Client` should be reused (i.e. it maintains a connection pool maybe?)

Perhaps clarifying these with some remarks, or fixing either the example code or the Close() godoc would help.

**Comment by ahmetalpbalkan** [comment]
Actually found one example where it is closed. https://godoc.org/cloud.google.com/go/datastore#ex-package--Auth But there are other 2-3 more visible examples that it isn't closed.

**Comment by jba** [comment]
If a client has a Close method, you should consider it a heavyweight object. Reuse if possible, and call Close when you're done (unless your program is terminating).

We should document the Close method better.

**Comment by ahmetalpbalkan** [comment]
@jba that'd be my gut feeling as well. However it's not immediately obvious to me. Moreover, what's not clear to me is: is Client doing connection pooling? If not, should I implement it myself, because I think my requests might be getting serialized if the client.conn is a single connection?

I found this to be a friction myself while developing an app on top of Datastore using Go, hence I’m reporting it. I think it would be helpful to document this explicitly. If the Client godoc would say "we do connection pooling for you, don't worry, just Close() when you're done", that'd be very ideal, but as you can understand, I still don’t know what the behavior is so my question still stands.

**Comment by ahmetalpbalkan** [comment]
@jba do you have any answers to my question above?

**Comment by jba** [comment]
The `cloud.google.com/go/datastore` client does not do connection-pooling by default Use the [WithGRPCConnectionPool](https://godoc.org/google.golang.org/api/option#WithGRPCConnectionPool) option to create a pool.

**Comment by ahmetb** [comment]
Should we document this behavior? I think it's worth being verbose about which clients do pooling, whether users should close clients and such semantics.

**Comment by jba** [comment]
Agreed.

**Comment by jba** [comment]
So the action item for this bug is: for each package in this repo, document:
- That Client.Close should be called (if it exists)
- Whether the client does connection pooling on its own
- How to create an underlying connection pool if it doesn't

**Comment by broady** [comment]
I feel like all clients should do pooling. Why doesn't it?

Having "GRPC" in the option name feels bad to me. We should avoid exposing implementation details like what type of transport is used. Why not just "WithConnectionPoolSize(int)"?

**Comment by jadekler** [comment]
Hello! Some of our clients use http, and some use grpc. In both cases we have connection pooling, but they are of different forms. Here are more details about these usages:

*http*

- HTTP clients use golang's net/http [default client](https://golang.org/pkg/net/http/), which supports pooling by caching existent connections for future re-use. This can be tweaked in the [http transport](https://golang.org/pkg/net/http/#Transport) by configuring `MaxIdleConnsPerHost` and `MaxIdleConns`.
- I believe that connections are used on a "first available" basis.
- I believe conns are spun down per client side `IdleConnTimeout` setting.

*grpc*

- Some gRPC clients use a custom [pool resolver](https://godoc.org/google.golang.org/api/internal#PoolResolver) (instead of one of [grpc's resolvers](https://github.com/grpc/grpc-go/tree/dfa18343df54bda471a4b53677aa7c0d0df882d1/resolver)). For pubsub, as an example, the pool resolver is configured to use [`GOMAXPROCS`](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/af36d1f996b5a38131ce2942f8ccbb3f86de2487/pubsub/pubsub.go#L67) (as mentioned before), although that can be changed with [`WithGRPCConnectionPool` option](https://godoc.org/google.golang.org/api/option#WithGRPCConnectionPool).
- This "pool" forces gRPC to open a transport connection to each address, and then round robin requests between the conns, as opposed to the aforementioned "first available" basis.
- I believe that conns are spun down per server side [`KeepAlive` setting](https://godoc.org/google.golang.org/grpc/keepalive#ServerParameters).

Answering some questions in this thread:

- I'm not sure that we can offer a ubiquitous `WithConnectionPool(size)`, since that guarantee isn't something we can make for http conns.
- All http clients implicitly use connection pooling.
- I'll dig in some more and take a look at what's happening for pooling across our grpc clients. There are [some other pools floating around](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/af36d1f996b5a38131ce2942f8ccbb3f86de2487/spanner/session.go) that I'm unfamiliar with. That said, it's safe to say that if you use `WithGRPCConnectionPool`, you will get pooling.
- I'll take a pass through our docs and see if we can clarify this setup.

**Comment by ahmetb** [comment]
@jadekler Thanks for the thorough work. It would be great to capture the gist of these deductions and filter those that are relevant to the users and include in package or Client godocs. For example, in storage.Client, I'd love to see something like "This client internally provides connection pooling.".

**Comment by jadekler** [comment]
SGTM, I'll make a doc pass on this.

**Comment by jadekler** [comment]
@ahmetb @broady Further investigation reveals that it's not easy to change HTTP transport settings, since supplying your own HTTP client causes [yours to be used](https://github.com/google/google-api-go-client/blob/master/transport/http/dial.go#L46-L48) immediately without getting [all the nice auth goodies that users normally get](https://github.com/google/google-api-go-client/blob/master/transport/http/dial.go#L54-L75).

Not sure if any user cares much about this (in my experience most people are very OK with [the default transport settings](https://github.com/golang/go/blob/master/src/net/http/transport.go#L47-L48)), but thought I'd mention.

**Comment by ahmetb** [comment]
I'm completely fine with not being able to update the settings, what I'm more interested in is surfacing the underlying transport/pooling information on the Client godocs.

**Comment by jadekler** [comment]
Closed as of https://github.com/GoogleCloudPlatform/google-cloud-go/commit/dfdc5040dbf96e12b7ad6d8080d0c8bd380cb8f2
