### ISSUE TITLE
storage: client.Close() & underlying connection pooling behavior not clear

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/google-cloud-go#530]
(Similar to #516) I am reading `storage` docs

- https://godoc.org/cloud.google.com/go/storage#Client.Close
- https://godoc.org/cloud.google.com/go/storage#NewClient

and these don't give me a clue whether I should be using short-lived `*storage.Client` every time I want to do a storage operation, or I should be using a single instance and Close() once I am done, or have a pool of `*storage.Client` instances in case internally it might be using a single TCP connection or whatnot and my requests might be serialized.

I think the package docs should make the behavior/suggested way of using clearer without requiring people to dig into the code to see what is going on under the hoods.

**Comment by ahmetb** [comment]
@jba it looks like [in the code](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/081f6b13d0132656829110e5f8344a13dfe039dc/pubsub/pubsub.go#L64) for some subpackages there is `option.WithGRPCConnectionPool`. Is this the case for other subpackages as well?

I see you have just labeled this as _documentation_ appropriately. It would be really nice to have clear statement in subpackages or root-package level explaining whether the caller should maintain a connection pool or if the client library subpackages do it for the user. IMO This piece of information matters a lot for people who want to write production-grade apps on top of client libraries.

**Comment by rakyll** [comment]
All cloud.google.com/go clients should be long-lived. Non-gRPC APIs initiates a http.Client per cloud client. Connection pooling is done at the http.Client-level; in order to be able to reuse the pool, you should reuse the cloud client instances.

**Comment by ahmetb** [comment]
@rakyll Great answers, thank you so much. We should totally write these down on the godoc. This answers the question for the non-gRPC packages. How about the gRPC clients, do they all maintain a pool as well?

Also, if customers are making high QPS requests to GCP APIs, is there any point in doing *.Client pooling? Would http.Client's internal connection pool be a bottleneck?

**Comment by jba** [comment]
@ahmetb Instead of pooling Clients, try the `WithGRPCConnectionPool` option. I'm afraid there are no easy answers: you'll have to experiment.

**Comment by jadekler** [comment]
Hi @ahmetb , I'll take a pass through our docs and document conn pooling. To answer your most recent questions:

- No, implementing pooling yourself is not needed. Since datastore is a gRPC client, use `WithGRPCConnectionPool` to achieve pooling. Some clients [pass this option by default](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/af36d1f996b5a38131ce2942f8ccbb3f86de2487/pubsub/pubsub.go#L67), but it's not guaranteed. Datastore does not.
- If customers are making high QPS requests, there is no point in doing client pooling. http.Client's internal connection pooling should not be a bottleneck. You should be able to create an http client with custom `MaxIdleConnsPerHost` and `MaxIdleConns` and pass the client in as a client option with [`WithHTTPClient`](https://godoc.org/google.golang.org/api/option#WithHTTPClient).

As mentioned, I'll take a pass through our docs and document pooling mechanics. Do you mind if I close this issue and track the docs pass in #516 ?

**Comment by ahmetb** [comment]
Sounds good.
