### ISSUE TITLE
datastore: types that implement PropertyLoadSaver can't load their key

### ISSUE THREAD

**Issue by alercah** [GoogleCloudPlatform/google-cloud-go#537]
9fd18ed4 made it possible to load a property from `__key__` to get the key when you `Get`. But because this is not a real property, a type which implements the `PropertyLoadSaver` interface has no way of accessing its key. Even using `Load` can't do it, because the information is never made available to the interface method.

**Comment by adams-sarah** [comment]
Hm, great point.

I don't think we want to change the `PropertyLoadSaver` interface, since so many folks are already using it, and it would be a rather big refactor. But we could add a `KeyLoader` interface, something like:
```go
type KeyLoader interface{
    LoadKey(k *datastore.Key) error
}
```
and your PLS could also implement `KeyLoader`.

The change to datastore pkg would be minimal. maybe ~5-10 lines. We would just need to add a check in `loadEntity` (https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/datastore/load.go#L339-L341) to also see if `dst` implements `KeyLoader`, and call `LoadKey` if it does.

Thoughts @rakyll @jba @zombiezen ?

**Comment by alercah** [comment]
Would it make sense to make it embed the PropertyLoadSaver interface to
make it clear that it is only useful if you also implement that interface?

It's a shame that adding __key__ as an artificial field to the property
array passed in is also potentially breaking.

**Comment by chaudharisuresh997** [comment]
The way google datstore is implemented its a shame.U say u have putmulti method but u cant pass it array or slice of struct so what sort of stuff u have done.U have given enough energy to this product.But u are not even giving any thought to back it with plenty of examples.Not enough testing.I am very depressed the way google datastore documenttation and apis are written I am loosing my mind bro
