### ISSUE TITLE
storage: obj.Update to Support Changing StorageClass

### ISSUE THREAD

**Issue by josephbergevin** [GoogleCloudPlatform/google-cloud-go#574]
Func: `func (o *ObjectHandle) Update(ctx context.Context, uattrs ObjectAttrsToUpdate) (*ObjectAttrs, error)`
(see [func here](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/storage/storage.go#L355))

_Problem_: The Update ObjectHandle method does not currently support updating the StorageClass of a storage Object.

**Solution**: Add `StorageClass optional.String` field to `ObjectAttrsToUpdate` struct and handle the logic in the same way as the other `optional.String` fields (`ContentType, ContentLanguage, ContentEncoding, ContentDisposition, CacheControl`) in the Update method:

```
if uattrs.StorageClass != nil {
  attrs.StorageClass = optional.ToString(uattrs.StorageClass)
  forceSendFields = append(forceSendFields, "StorageClass")
}
```

If I'm overlooking something, let me know. Otherwise, I'm happy to take care of this and submit a PR.

**Comment by c0b** [comment]
+1 need this

**Comment by jba** [comment]
I don't believe you can update an object's storage class this way. See https://cloud.google.com/storage/docs/changing-storage-classes. You have to copy the object onto itself. (Makes sense, since changing the storage class may involve more than just changing the metadata, like writing the object to a different medium or location.)

For an example in Go, See [TestIntegration_PerObjectStorageClass](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/storage/integration_test.go#L1003).
