### ISSUE TITLE
semver release tags

### ISSUE THREAD

**Issue by adams-sarah** [GoogleCloudPlatform/google-cloud-go#595]
similar to https://github.com/google/google-api-go-client/issues/198

**Comment by adams-sarah** [comment]
Oops, we already do this.

**Comment by jba** [comment]
Sorta, but not correctly or reliably. I think it's worth having an issue to discuss.

**Comment by fd** [comment]
It would also be nice to have some sort of coordinated versioning between `google/google-api-go-client` and `GoogleCloudPlatform/google-cloud-go`. Currently it is unclear which versions are compatible (and tested).

**Comment by alanma** [comment]
up for this request. Am using glide and would love semver working properly so I could reliably using the following:

```
- package: cloud.google.com/go
  version: ~0.7.0
```

**Comment by jba** [comment]
We are now tagging with v0.X.0 periodically (approximately weekly). So tools like dep and glide that don't pin to a specific version should get approximately tip. And when they do pin, it will be more granular.

We still aren't using semver fully, which is why our first digit is still zero. We don't distinguish between breaking and non-breaking changes when we tag. Considering that this repo includes packages that range from mature to experimental, it's likely that every week introduces a breaking change.

**Comment by jba** [comment]
Moved to https://github.com/GoogleCloudPlatform/google-cloud-go/wiki/Long-Term-Plans.
