### ISSUE TITLE
all: deflake unit tests

### ISSUE THREAD

**Issue by rakyll** [GoogleCloudPlatform/google-cloud-go#602]
Units tests are failing too often due to flakiness which makes it impossible for us to rely on them. Please deflake the unit tests to make them useful again.

/cc @adams-sarah

**Comment by adams-sarah** [comment]
+1 yes it's this test specifically:
 --- FAIL: TestEmptyObjectIterator (0.08s)
	storage_test.go:657: timed out

Started failing after @jba introduced t.Parallel into some of the storage tests (https://code-review.googlesource.com/#/c/11971/)
We could just roll that back.

Sent him an email anyway, waiting for his thoughts since it was his CL.

TBH i don't see why we need a timer in a unit test. We should be mocking instead.

**Comment by adams-sarah** [comment]
nvm, made a CL. I think @jba's got a lot on his plate:
https://code-review.googlesource.com/#/c/12190/
