### ISSUE TITLE
storage: Copy() detect service-account access error 

### ISSUE THREAD

**Issue by yazgoo** [GoogleCloudPlatform/google-cloud-go#643]
Hi, I'm doing a simple copy like this:

```
    bkt := storageClient.Bucket(bucket)
    obj := bkt.Object(destPath)
    w := obj.NewWriter(context)
    defer w.Close()
    r, err := os.Open(sourcePath)
    if err != nil {
      return err
    }
    defer r.Close()
    written, err := io.Copy(w, r)
    log.Printf("copyFilesToStorage: wrote %d bytes to %s\n", written, destPath)
    if err != nil {
      return err
    }
    return nil
```

When running this with a service-account with no storage rights whatsoever, of course the files don't get written, but I get no error from `Copy()` and `written` is equal to source file size.

Shouldn't `Copy()` return an error ?
If not, what is the good way to check for such errors ?

Thanks

**Comment by jba** [comment]
You should probably check the error returned from `w.Close()`.

It's generally OK to ignore the error returned from `Close` when reading a file, but you should always check when writing, because an implementation may buffer the writes until `Close` is called.

If you still don't see an error after that, we'll take a closer look.

**Comment by yazgoo** [comment]
Thanks @jba, using `Close()` returns value works.
