### ISSUE TITLE
errors: move package to errorreporting

### ISSUE THREAD

**Issue by rakyll** [GoogleCloudPlatform/google-cloud-go#674]
The autogenerated layer is under errorreporting, and we should keep the handcrafted one closer to the autogenerated client for discoverability and consistence.

/cc @jba

**Comment by jba** [comment]
Agreed. Will do.

**Comment by rakyll** [comment]
@jba, is this happening? Can I make the move if you don't have time?

**Comment by jba** [comment]
Yes, please do.

**Comment by nightlyone** [comment]
And it is pretty annoying, that it is called "errors". Clashes with the stdlib errors package and also with Dave Cheneys awesome error wrapping package at github.com/pkg/errors

**Comment by pongad** [comment]
The name `errorreporting` feels rather long. As noted in [CL](https://code-review.googlesource.com/#/c/gocloud/+/15670/), I think we should consider moving both the handwritten and generated client to somewhere with shorter package name.

@jba raised a good point that since other langs call this `errorreporting`, we should do the same thing.

@rakyll Do you have an opinion?

**Comment by pongad** [comment]
Package "errors" has been deleted, closing this
