### ISSUE TITLE
logging: Flush should return an error if any of the logs failed

### ISSUE THREAD

**Issue by campoy** [GoogleCloudPlatform/google-cloud-go#677]
Currently `Log` will not return an error and neither will `Flush`.

This means that my only option to wait for all the previous entries to be logged successfully is to `Close` the client.

cc: @rakyll

**Comment by jba** [comment]
You want to set Client.OnError at the start of your program. That function will be called with errors.

Close doesn't even do what you want&mdash;it doesn't report errors from logging RPCs, only from the close of the log client.

This probably could be clearer in the docs, and there should be an example somewhere, right?

**Comment by rakyll** [comment]
We need an example to make this clear. Currently, we document that Close flushes all the loggers. Normally, users should be expecting that the RPC errors to be returned from Close if something goes wrong during flushing.

**Comment by campoy** [comment]
I'm using this library in a piece of code that is supposed to be quite simple.

Look at this line, and tell me if there's a less awful way of writing that code correctly
https://github.com/campoy/logpipe/blob/why/logpipe.go#L95

**Comment by jba** [comment]
```
client.OnError = func(err error) {
    log.Printf("error received: %v", err)
    select  {
        case <-errc:
        default: close(errc)
   }
}
```
Then select on `<-errc` in your loop, just so you can break.

No additional error-handling code after calling Flush.

**Comment by campoy** [comment]
I want any errors to stop the program, that's why I'm sending them to the channel and I handle them from the main loop.
How would that work? 

This is unnecessarily complex, abusing Go concurrency features to compensate for a poorly designed API.

**Comment by rakyll** [comment]
After spending an hour and watching @campoy working on this, I totally agree. Flushing errors shouldn't be this complicated. It is a fundamental feature. We only encourage people not to handle them by asking them to work with a highly complicated API.

Once a user calls Close, they are literally done with the client. We shouldn't expect them to use these additional APIs to handle the errors via client hooks.

**Comment by jba** [comment]
> I want any errors to stop the program, that's why I'm sending them to the channel and I handle them from the main loop.

That is the code I gave you, I think. It closes a channel to indicate that an error occurred, and your main loop selects on that channel. There's no need to write the error to the channel, since you can just print it from the handler.

> Once a user calls Close, they are literally done with the client. We shouldn't expect them to use these additional APIs to handle the errors via client hooks.

I don't understand the connection between these two sentences. Maybe you're saying that Close should return an error if anything went wrong during the lifetime of the client? We could do that. Are you sure that's what you want?

Here are the issues for the logging client:
* Logging must be asynchronous and fast. We can't do an RPC for each log message; we have to buffer them. Therefore, Log cannot return a meaningful error.
* Also, most of the time you don't want to check the Log call for errors. Logging is often a best-effort sort of thing, and if there are errors you either don't care at all or you just want to note them and proceed. So if the Log call was the only way to get errors, it would be inconvenient for many use cases.
* Flush could return an error. But since log entries may be flushed at any time, and the Flush call you're making now might not fail, it might return nil when in fact there was an earlier error.
* If Log/Flush/Close did report all the errors that had happened since the last call, the client would have to remember them, which could result in unbounded memory use.
* Log/Flush/Close could report the last error, or the first, but that doesn't tell you much. Did I drop one log entry? Insignificant. Did I drop all of them? Probably bad. What about 5%? I don't know, maybe that's okay. What if I ran for a day, but the logging service was unavailable for 5 minutes, so I lost a 5-minute chunk of logs, but nothing else? I probably don't care. What if a few of my log entries are malformed, so they return InvalidRequest errors, but the rest are fine? I want to fix that bug. My conclusion is that there must be a way to get every error that occurs.

Happy to consider a different design for v2 that handles all the above.

**Comment by jba** [comment]
I don't think we can blame Brad for this. OnError was my idea, I think.

**Comment by broady** [comment]
Maybe Flush should return an error, since it blocks, anyway? Report the error both as a return value as well as the OnError callback.

Also, @campoy's program shouldn't call Flush, Close says that it flushes then closes the client.

**Comment by jba** [comment]
@broady, that sounds reasonable.

@campoy, I think one reason this is hard is that stopping the program on the first log error is unusual. If they are debug logs, you don't care. If they are accounting logs that translate to revenue or some other valuable commodity, you probably still don't want to crash, because you'll make more money if you keep going (assuming the errors are transient). If the logs are used for security auditing, then you probably want to keep going and just deny permission.

**Comment by jba** [comment]
@broady but which error should Flush return?

**Comment by rakyll** [comment]
> Maybe you're saying that Close should return an error if anything went wrong during the lifetime of the client? 

Close should return an error if flushing fails with an error.

It can buffer all the errors in a slice and return a wrapper return all the errors:

```
type FlushError struct {
    Errors []error
}
func (e FlushError) Error() string
```

**Comment by campoy** [comment]
This is what I would expect:

`Flush` blocks until all logs have been sent, and returns an error if any of the logging operations failed since last call to `Flush`, if any.

`Close` calls `Flush` and returns an error if it fails, or if any of the other things that `Close` does fails. Calling `Log` or `Flush` after `Close` is an error, maybe even a panic.

I'm very scared of the `OnError` mechanism, introducing data races is too easy making everyone's code brittle.
If `Flush` returned an error it would allow me to verify the auth is correct by simply doing:

```go
logger.Log("server is starting")
if err := logger.Flush(); err != nil {
    log.Fatalf("could not log: %v", err)
}
```

**Comment by jba** [comment]
> It can buffer all the errors in a slice and return a wrapper return all the errors

That leads to unbounded memory consumption, as I mentioned. Imagine you log a million entries and they all fail.

**Comment by jba** [comment]
> If Flush returned an error it would allow me to verify the auth is correct.

Use [Ping](http://godoc.org/cloud.google.com/go/logging#Client.Ping) for that.

> Flush blocks until all logs have been sent, and returns an error if any of the logging operations failed since last call to Flush, if any. Close calls Flush and returns an error if it fails, or if any of the other things that Close does fails. 

I can do that. I'll make a CL in the next couple of days. I understand why people think that is useful.

But let me explain why it isn't useful. I actually said it above, but I'll try again, since no one addressed my points.

The logpipe program is designed incorrectly. It should not fail on the first log error. The best it can do is to write log errors to stderr and let humans decide what to do. That is (surprise!) the default behavior of the logging client. (But if you did want to exit on the first error, just put `os.Exit` into the `OnError` function and don't bother with all the synchronization.)

Arguably, logpipe shouldn't exit with failure even if there were any errors from the logging service. (Do you really want your 8-hour pipeline to fail because one debug log message didn't get written?) Maybe it should only fail if all or most of the RPCs failed. I don't know what the right behavior is, actually, but that's exactly why nothing that Flush or Close could return would be useful  (short of all the errors, which takes too much memory).

I think at the heart of the problem is your view that the logging service is like a database or a file system, where an error means data loss, which must be dealt with. I think of it as a best-effort fire-and-forget service, where a little bit of data loss probably doesn't matter (but a lot does). Since it's impossible to know what errors matter, the best the client can do is make all the errors available and let the user decide. Any one error returned from Flush or Close will be at best an approximation. It's unlikely to be actionable. If an action is taken, it's likely to be `log.Fatal`, which is almost certainly too dramatic.

(I'm sure you've never written a Go program that exits when `log.Print` fails. I'm sure because `log.Print` doesn't return an error.)

So I think that the right way to treat the error from `Close` (which will include the error from `Flush`) is the same way we treat the error when we close a file after reading it:
```
defer client.Close()
```

**Comment by campoy** [comment]
Ok, so `Ping` is probably what I wanted all this time, since I don't care about a program failing to log *some* entries, but I do care when none of my logs are being sent successfully.

In that case a program that works correctly (R), meaning it checks that it is possible to log something at startup time and then checks whether there was any error at exit would be something like:

```go
func main() {
	ctx := context.Background()
	client, err := logging.NewClient(ctx, opts.ProjectID)
	if err != nil {
		log.Fatalf("Failed to create client: %v", err)
	}
        // I ignore this error, but I could check it if I wanted to see if any logs failed
        defer client.Close()

        if err := client.Ping(ctx); err != nil {
               log.Fatalf("Could not send initial ping: %v", err)
        }

       doStuffThatLogs(ctx, client.Logger("some-name"))
 }
```

Is there any way to add the check that `Ping` does to `NewClient`?
If that was the case I would not have tried to catch logging errors to start with.

At least, `Ping` should be added to the package level doc showing how to create a client.

PS: thanks for your very informative answer!

**Comment by jba** [comment]
I'm sympathetic to doing a Ping in NewClient. Calls to NewClient should be rare, so the performance hit should be minimal. And if _you_ couldn't figure out that all you needed was an initial ping, then approximately no one could.

@bradfitz and @zombiezen, what do you think?

**Comment by zombiezen** [comment]
Calling `Ping` on creation seems reasonable, but bear in mind that GCP clients aren't always created just once per program (App Engine Standard).

I'm curious what Stackdriver Log clients for other languages are doing for this.  I would expect the `Flush` docs to at least mention the `OnError` to avoid this confusion in the future.

**Comment by campoy** [comment]
I wonder if there's some way to do a dry-run of a log, so it doesn't appear on the logs but it does verify everything else

**Comment by jba** [comment]
@campoy I remember looking into this issue when I wrote the client. I couldn't find any way to verify permission short of actually writing a log entry. I even talked to the logging team about it.
