### ISSUE TITLE
bigquery: InferSchema doesn't return error when embedded struct has `interface{}`

### ISSUE THREAD

**Issue by suzuken** [GoogleCloudPlatform/google-cloud-go#708]
When we use embedded struct on `bigquery.InferSchema`, I guess that will cause error when embedded struct use unsupported types like `interface{}`.

Example:

```go
package main

import (
	"fmt"

	"cloud.google.com/go/bigquery"
)

type T struct {
	A interface{}
}

func main() {
	cases := []interface{}{
		// cause error. it's working as intended.
		struct{ M map[string]interface{} }{},
		struct{ M interface{} }{},

		// its' normal. no problem.
		struct{ M string }{},
		struct{ M int }{},

		// embedded struct has interface{}, but it's passed.
		struct {
			T
			A, B int
		}{},

		// it's cause infer error.
		struct {
			M map[string]interface{}
			A int
		}{},
	}
	for i, c := range cases {
		_, err := bigquery.InferSchema(c)
		if err != nil {
			fmt.Printf("#%d: %v cause infer error: %s\n", i+1, c, err)
		}
	}
}

```

Output:

```
#1: {map[]} cause infer error: bigquery: unsupported type of field in struct
#2: {<nil>} cause infer error: bigquery: unsupported type of field in struct
#6: {map[] 0} cause infer error: bigquery: unsupported type of field in struct

```

I expected `bigquery.InferSchema` on case 5 will be failed, but it's passed. Does it working as intended?

**Comment by pongad** [comment]
This is a little subtle. Embedded an interface is an error . However, case 5 has two fields called `A`. One in an `int` and another an `interface{}`. Since it's embedded, the `A interface{}` is deeper down in the hierarchy. By the rules we copied from pubsub, `A interface{}` is hidden and does not take part in marshaling or unmarshaling, so `InferSchema` never checked it.

We could choose to do nothing. After all, reads and writes should work OK (I think!). On the other hand, this could cause surprising behavior. If the user deletes `A int`, thinking that it would remove a field from the schema, they'll see an error instead.

One way to fix is to make `fieldcache` also return fields that should be otherwise ignored and just check them without adding them to schemas.

@jba I can pick up this work if we agree on the approach.

**Comment by jba** [comment]
The shadowing of the `A interface{}` by the `A int` in case 5 is a property of the language. From the spec:

> For a value x of type T or *T where T is not a pointer or interface type, x.f denotes the field or method at the shallowest depth in T where there is such an f. If there is not exactly one f with shallowest depth, the selector expression is illegal.

We correctly infer the schema to consist of two integer fields named `A` and `B`, so case 5 is WAI.
