### ISSUE TITLE
storage: should offer a way to set Content-Length for uploads

### ISSUE THREAD

**Issue by stapelberg** [GoogleCloudPlatform/google-cloud-go#724]
https://github.com/GoogleCloudPlatform/google-cloud-node/issues/601 is related

Without specifying Content-Length, Google Cloud Storage can’t tell whether a request successfully completed, it can only see that the client stopped sending data.

The omission of a Content-Length header contributes to a subtle data corruption bug in code which uses the following pattern:

```go
func upload(…) error {
	var err error
	wc := client.Bucket(bucket).Object(object).NewWriter(ctx)
	defer wc.CloseWithError(err)
	_, err = io.Copy(wc, f)
	return err
}
```

In case the program panics (e.g. in the io.Reader `f`, or unrelatedly due to memory pressure), deferred statements will still be executed, so `wc.CloseWithError(nil)` (note the `nil`!) is called, which results in the underlying `io.PipeWriter` returning `io.EOF`, just like when a file is successfully read.

Upon panic, two things can happen:

1. The program recovers from the panic, and the uploaded file will be incomplete (!).

2. The program terminates. The upload probably times out, but I don’t know for sure (and can’t find any docs) how the server side handles that (especially without a Content-Length header).

I see a couple of things to improve:

1. Remove `CloseWithError` entirely. I don’t see how it differs from `Close`? Is there a real-world use-case for it?
2. Document that CloseWithError shouldn’t be called from defer statements (as a precaution).
3. Introduce the Content-Length header so that the server side can discard incomplete uploads.

cc @mpvl @merovius

**Comment by Merovius** [comment]
The example code is buggy regardless; `defer` evaluates the arguments to the function call directly, so the given code will *always* pass `nil`, even in the absence of panics. The correctly wrong idiom (to illustrate the issue) would be

```
func upload(…) error {
	var err error
	wc := client.Bucket(bucket).Object(object).NewWriter(ctx)
	defer func() { wc.CloseWithError(err) }()
	_, err = io.Copy(wc, f)
	return err
}
```

and the correctly correct idiom would be

```
func upload(…) error {
	var err error
	wc := client.Bucket(bucket).Object(object).NewWriter(ctx)
	defer func() {
            if err != nil {
                wc.CloseWithError(err)
            }
       }()
	_, err = io.Copy(wc, f)
        if err != nil {
            return err
        }
	return wc.Close()
}
```

Not contending that the API makes it relatively easy to write the wrong code (as illustrated). But a) I see a good argument for having `CloseWithError` to explicitly roll back and clean up resources in the error-case, so I don't think 1 is an adequate solution and b) I believe `CloseWithError` *needs* to be called from a defer to ensure the correct cleanup of resources in case of a panic (if you care); just in the correct way, so 2 isn't an adequate solution either.

I'm not familiar with the implementation (and frankly too lazy right now to look it up :) ), but how is Close implemented? Does it literally just close the connection to the server and the server thus assumes the write was successful, or does it include some explicit commit-action? And if so, how does CloseWithError change that?

It seems 3 is needed/useful iff the protocol does not do an explicit commit. If it does, then it's irrelevant what the Content-Length is, as it won't commit anyway on short writes. If it doesn't, short writes could happen for any number of reasons (like cut fibers or power outages), so it's a bad idea to not guard against them and Content-Length seems like a good way.

All of that being said, how to correctly commit a write should definitely be documented, because evidently it's non-trivial and can contain subtle bugs :) I'd also argue that `CloseWithError` should probably rollback a write even if nil is passed (thus making it possible to elide the nil-check).

**Comment by stapelberg** [comment]
Thanks for the correction.

Close doesn’t include an explicit commit, and neither does CloseWithError do any explicit rollbacks. AFAICT, Google Cloud Storage’s API supports neither.

To expand on my suggestion ①: `defer wc.Close()` should be called instead of wc.CloseWithError, at which point CloseWithError could be removed.

**Comment by jba** [comment]
We upload in chunks. Each chunk has a Content-Length. See https://github.com/google/google-api-go-client/blob/master/gensupport/resumable.go#L65.

If you really want to make sure your data landed OK, set `MD5` or `CRC32C` on the `Writer`. If you use `CRC32C`, make sure you also set `SendCRC32C`.  http://godoc.org/cloud.google.com/go/storage#Writer. (Note that the first two fields are on `Writer` via the embedded `ObjectAttrs`.)

**Comment by stapelberg** [comment]
Thanks for the reply.

The ObjectAttrs.CRC32 field docstring states “This field is read-only.”, which seems to contradict setting it when uploading data…?

Could we extend the documentation to clarify that the effect of sending a CRC32 is that GCS can discard invalid uploads?

Also, could we add some sample code which demonstrates the use of CRC32?

I’m happy to send a PR for either.

**Comment by jba** [comment]
https://code-review.googlesource.com/15852

**Comment by stapelberg** [comment]
Great, thank you very much!

**Comment by dneralla** [comment]
Hi @jba We are facing a similar issue where the uploader is uploading 0 bytes.

Per your comment 
https://github.com/GoogleCloudPlatform/google-cloud-go/issues/724#issuecomment-321873549

That goes through that path when the content being uploaded is greater than chunksize per 
https://github.com/google/google-api-go-client/blob/master/storage/v1/storage-gen.go#L8751

And MediaBuffer is only created when content is greater than chunk size for resumable upload, per 
https://github.com/google/google-api-go-client/blob/master/gensupport/media.go#L191

What happens on retries when it doesn't go through resumable upload ?

**Comment by jba** [comment]
@dneralla I'll look into it.

**Comment by dneralla** [comment]
@jba  Do you want me to file an other issue ? 
`   
      delta := rand.Int31n(3)
      if delta < 2 {
          return nil, &googleapi.Error{
              Code:   503,
              Header: res.Header,
          }
      }
`
I added something like the above in https://github.com/google/google-api-go-client/blob/master/storage/v1/storage-gen.go to simulate retries. 
 
On the uploads greater than chunksize it was able to upload fine but on uploads less than chunksize it just uploads zerobyte files.
