### ISSUE TITLE
API for Compute Engine

### ISSUE THREAD

**Issue by ae6rt** [GoogleCloudPlatform/google-cloud-go#744]
Is this the repository that one would watch to be alerted to an API that allow management of Compute Engine?

**Comment by jba** [comment]
Probably not. Our current compute API clients are at https://godoc.org/google.golang.org/api/compute (from repo https://github.com/google/google-api-go-client). That's not likely to change anytime soon.

**Comment by DazWilkin** [comment]
jba@ it's remarkable that Compute Engine is not supported by a Golang Cloud Client Library.

Is this a result of the velocity of the Compute Engine API? Or resourcing?

A consequence -- of course -- is that developers need to fallback to the API Client Library and miss out on -- to [quote Google](https://cloud.google.com/apis/docs/cloud-client-libraries):

"...our latest and recommended client libraries for calling Google Cloud APIs. They provide an optimized developer experience by using each supported language's natural conventions and styles. They also reduce the boilerplate code you have to write because they're designed to enable you to work with service metaphors in mind, rather than implementation details or service API concepts"

**Comment by jadekler** [comment]
@DazWilkin This thread is quite old. Please open a new issue to discuss. :)
