### ISSUE TITLE
How to avoid urlfetch DEADLINE_EXCEEDED errors for BigQuery job inserts ?

### ISSUE THREAD

**Issue by nomoth** [GoogleCloudPlatform/google-cloud-go#775]
Hi,

Some context : I wrote a bigquery jobs scheduler which now runs in production and schedule hundreds jobs each day. And maybe once per week, I got one or two jobs failing for DEADLINE_EXCEEDED on Job insertion.

The error is :
Post https://www.googleapis.com/bigquery/v2/projects/iscool-scheduler/jobs?alt=json: API error 5 (urlfetch: DEADLINE_EXCEEDED)

I tried to change the context deadline to 60s but it does not change anything, the job failed after 5s.
```
ctx, cancel := context.WithTimeout(ctx, 60*time.Second)
defer cancel()
loader.Run(ctx)
```

Do I need to set the deadline at the client creation ?
By the way, is there a way to recognize UrlFetch error without looking for DEADLINE_EXCEEDED in the error message?

Thanks

**Comment by jba** [comment]
On AppEngine, you must set the deadline in the context that you pass to `NewClient`.

> By the way, is there a way to recognize UrlFetch error without looking for DEADLINE_EXCEEDED in the error message?

If you print the error with "%T", you should see something like "*internal.APIError". Unfortunately you can't cast to that type, because it's internal, and you can't rely on that name being stable. So probably looking for "DEADLINE_EXCEEDED" is more reliable.
