### ISSUE TITLE
storage: Implement a ResumableObjectWriter

### ISSUE THREAD

**Issue by rakyll** [GoogleCloudPlatform/google-cloud-go#78]
Storage package should support resumable uploads due to the urlfetch body size limitation. App Engine users should be depending on the resumable uploads if the file size is larger than 10MB.

See https://cloud.google.com/storage/docs/json_api/v1/how-tos/upload?&_ga=1.73911639.470265211.1407285034#resumable for details.

cc/ @gmlewis

**Comment by bradfitz** [comment]
I'd rather just see this be automatic.

I just tried to upload a 5 GB file and it failed (on Close, oddly) with:

```
2015/05/10 16:58:46 Writer.Close = Post https://www.googleapis.com/upload/storage/v1/b/bradfitz-foo/o?alt=json&uploadType=multipart: write tcp 10.0.0.128:50567->216.58.216.170:443: write: broken pipe
```

We should buffer any un-acked data on the Writer, and flush periodically to bound memory requirements. The user could configure on the Writer what the flush size is.

**Comment by rakyll** [comment]
I'd prefer an incremental writer that accepts an io.ReadSeeker. A parametric buffer size sounds good in theory, but will be hard to determine/optimize the size when concurrency is involved.

**Comment by Karthic-Hackintosh** [comment]
This issue remains unresolved and as writing larger files with the storage writer is critical to our product, we remain rather frustrated that this has not been fixed. Given our startup is one of those selected for a large Google Cloud Platform credit as part of their Startup award last year to build and deploy our MVP, we are in thick of building alpha on GCP. However, we will have no product if we do not have the ability to write larger files on the bucket using:
    
    wc := storage.NewWriter(gcs.Ctx, bucketName, fileName)  
    wc.Write([]byte)

Can we get a definitive response on how and when this will be fixed? Honestly, what worries us is that it has been open for so long, that this may not be a high priority internally. We are hopeful we can convince you to issue a fix ASAP, so that we can continue. Else we will have to be forced to make some major (and not so fun) decisions.

Really appreciate the assistance on this, especially @rakyll on the Slack channel. Bringing this to the attention of @bradfitz and @gmlewis as well.

**Comment by bradfitz** [comment]
@Karthic-Hackintosh, there's progress on this front happening here: https://code-review.googlesource.com/#/c/2762/

I also need this and regularly hit this. It's been frustrating me too.

I'm still catching up after ~month away on vacation & trips, but I'll try to figure out what the status is here and see how I can help, if possible.

**Comment by Karthic-Hackintosh** [comment]
@bradfitz , Thank you for the prompt response . Will be hoping and waiting for an update and a quick fix on this issue .

**Comment by gmlewis** [comment]
I've actually had a local working version of cloud/storage that uses resumable uploads and an example app that uses it, but to be honest, I haven't had the time to productionize it... write unit tests, integration tests, etc.

The update that @bradfitz pointed to will change the API, so I should probably hold off sharing my experimental changes.  Contact me directly, though, if you want to see my experiment before then.

**Comment by Adori** [comment]
@rakyll @bradfitz @gmlewis @okdave 
Has this issue been resolved? We are facing a roadblock in our process (all in Go), and if we can't handle larger than 10MB, we will have to do an enormous amount of (unnecessary) rewriting (for e.g. Java) to go around this issue. Also add 'handling' overhead to deal with two implementation stacks in GCP. Can you provide an update? 
cc: @Karthic-Hackintosh

**Comment by mcgreevy** [comment]
I'm sorry that this issue is getting in your way.  It's clearly important that this be fixed and I am working on it at the moment.  Taking into account downtime over the upcoming holiday period, I estimate it will be finished some time in the first two weeks of January.

**Comment by Adori** [comment]
@mcgreevy Thank you for responding promptly, and giving us an update on this. We really appreciate that you are working on resolving this. However, we have a our alpha coming out in January, we are not sure how to now to get this done in time. Our current status is that we have completed building our codebase (GO), with 3 critical media (file) pipelines that use this (ResuableObjectWriter), but have been forced to use files that are less than 10MB. This is highly artifical and we obviously cannot even go into a closed alpha given that the median size of files we are supposed to be ready to handle are around 30 to 40MB in general. We deeply respect the holiday season in front of all us, and value precious family time, but thought we would frankly share our situation with you as well.
We won a Google Cloud for Startup Award and specifically chose Go, not because it was a the latest shiny toy, but because it was so tailormade for our application. But after building for over 6 months, we were stunned to run into this issue. As I said the work around will involve a complete rewrite as this issue does not seem to exist in Java (our next most comfortable language). You will agree with me that for a small 5 member team (2 on the backend), this would crush us. So the sooner we can resolve this, the better. Please also let us know if we can be of any assistance (testing etc.). 
@rakyll @bradfitz @gmlewis @okdave @Karthic-Hackintosh

**Comment by okdave** [comment]
@Adori in your use case, do you know the final size of the object when you begin uploading it? Are you able to represent the incoming data as a `io.ReaderAt`, or is seeking impossible in your use case?

**Comment by okdave** [comment]
Also, in case we can't address this in time for your launch, do you think [composite objects](https://cloud.google.com/storage/docs/composite-objects) would be able to help in your case? That would let you upload separate object chunks (in parallel even), and compose them into a single object for your users.

**Comment by derekperkins** [comment]
Is there a chance that #146 will be implemented soon?

**Comment by okdave** [comment]
It's definitely on my radar, yes.

**Comment by Adori** [comment]
@okdave Thanks again for the suggestions. Unfortunately, while we know final size of object, our use case does it make impossible to seek. Composite Objects maybe an option (assuming you mean write under 10MB objects in GCS to avoid current problem, and then compose them into one single object). However, reluctant to do explore this as this will break other parts of our process which involves some identification/automation as soon as object is created, and we will have to create "wait" logic etc. Also given @derekperkins comment about #146, not sure if Composite of existing GCS objects will even work.
Happy to hear more suggestions, while waiting for the bigger fix to this issue comes in ASAP? :-|
Thanks again

**Comment by okdave** [comment]
@Adori we should have something to share early next week.

**Comment by derekperkins** [comment]
@okdave something for ResumableObjectWriter or for composite objects?

**Comment by derekperkins** [comment]
He says as he sits down to write a composite function. :)

**Comment by Adori** [comment]
@okdave Thanks and we await with bated breath! :-))

**Comment by okdave** [comment]
So, there are two pending patches which will bring this into the veneer library. Both are still experimental, so the API is subject to change.

One is a fix the underlying generated API:
https://code-review.googlesource.com/#/c/3930/
And the other is to expose to this through API:
https://code-review.googlesource.com/#/c/3931/

(You'll need to patch the first into `$GOPATH/src/google.golang.org/api` and the second into  `$GOPATH/src/google.golang.org/cloud`).

The use is quite simple:
```
w := client.Bucket("bucket").Object("obj").NewWriter(ctx)
w.Resumable = true
_, err := w.Write([]byte("hello world"))
```

One thing I'd stress is changing the variable `chunkSize` in [googleapi.go](https://github.com/google/google-api-go-client/blob/master/googleapi/googleapi.go#L361). The constant needs to be a multiple of 256kB, but 256kB by itself is far too small to get [useful throughput](https://en.wikipedia.org/wiki/Bandwidth-delay_product). I'd suggest moving it to close to your maximum chunk size (8MB say?). We'll definitely make this configurable before finalising this API.

**Comment by nightlyone** [comment]
The part in the generated API is finished (see https://godoc.org/google.golang.org/api/storage/v1#ObjectsInsertCall.Media ) and now work in this repo can begin.

**Comment by okdave** [comment]
This repo already has resumable support. The only part that remains is being able to configure resuming (for example, customise the maximum chunk size) – but for most cases it should be working directly already.

**Comment by RPGillespie6** [comment]
This would be nice for overcoming Google App Engine's 32MB request size limit (i.e. use a resumable upload to write the object out in 32MB chunks). Unfortunately, since this tool handles all the resumable stuff automatically without giving the user any control, it seems impossible to use the resumability feature across requests.
