### ISSUE TITLE
pubsub: Receive(..) does not honor context.Context

### ISSUE THREAD

**Issue by jadekler** [GoogleCloudPlatform/google-cloud-go#848]
When I pass a cancellable context to `Receive`, I expect to be able to call my cancelFunc and immediately have `Receive` stop blocking.

If `Receive` has not received any messages yet, this works as expected. Once `Receive` has received at least 1 message, it never stops blocking.

The following program demonstrates this problem:

```
package main

import (
	"context"
	"fmt"
	"cloud.google.com/go/pubsub"
	"github.com/satori/go.uuid"
	"time"
)

func main() {
	ctx, cancelFunc := context.WithCancel(context.Background())

	client, err := pubsub.NewClient(ctx, "<SOME-PROJECT>")
	if err != nil {
		panic(fmt.Sprintf("Failed to create client: %v\n", err))
	}

	t := client.Topic("send_queue")
	if t == nil {
		panic("Expected topic not to be nil")
	}

	s, err := client.CreateSubscription(ctx, fmt.Sprintf("some-subscriber-%s", uuid.NewV4().String()), pubsub.SubscriptionConfig{Topic: t})
	if err != nil {
		panic(err)
	}

	go func() {
		time.Sleep(10 * time.Second)
		fmt.Println("Cancelling")
		cancelFunc()
	}()

	fmt.Println("Listening..")

	err = s.Receive(ctx, func(c context.Context, msg *pubsub.Message) {
		fmt.Println("Got message!")
	})
	if err != nil {
		panic(err)
	}
	fmt.Println("Done")
}
```

Note that the async go func cancels the context in 10 seconds; I expect the program to exit at this point, but if any messages have been received the program hangs (at `s.Receive(..)` indefinitely).

**Comment by jadekler** [comment]
Not sure if intentional or not, but replacing `cancelFunc()` with `client.Close()` causes `err = s.Receive(..)` to return an error as opposed to gracefully closing. If that's not intended, I'm happy to create another issue.

**Comment by Bo0mer** [comment]
You should either `Ack` or `Nack` the message:

```go
	err = s.Receive(ctx, func(c context.Context, msg *pubsub.Message) {
		defer msg.Ack()
		fmt.Println("Got message!")
	})
```

This way, cancelling the receive operation behaves as you expect (I've changed the cancel function to be called after 2 seconds):
```text
19:29:20 main.go:41: Listening..
19:29:20 main.go:45: Got message!
19:29:22 main.go:37: Cancelling...
19:29:22 main.go:50: Done
```

Cheers,
Ivan

**Comment by jadekler** [comment]
@Bo0mer I rather think the user should not have to `Ack`/`Nack`. Per [the documentation for context](https://blog.golang.org/context), 

> The Done method returns a channel that acts as a cancelation signal to functions running on behalf of the Context: when the channel is closed, the functions should abandon their work and return.

I think the `Receive` function should - as the documentation say - abandon work promptly.

**Comment by jba** [comment]
The doc for Receive does say "If ctx is done, Receive returns nil after all of the outstanding calls to f have returned and all messages have been acknowledged or have expired." But it's buried a few lines from the top.

We discussed this issue when designing Receive. It was important to us that when Receive returned, there were no outstanding goroutines and the subscription streams to the server were all closed. If Receive returned with unacked messages, then any attempt to ack them later would fail, and we didn't want that.

In a way, this behavior is pointing to a flaw in your program: it's not being a good subscriber, because even though it knows it can't work on some messages, it doesn't nack them, forcing other subscribers to wait until they expire. Ideally, a well-written subscriber should only fail to nack if it dies unexpectedly.

Admittedly, using Context.Cancel to terminate Receive brings along some unintended expectations about Context.Done, as you pointed out. We understood that, but ultimately chose the design we thought was best overall.

**Comment by jadekler** [comment]
👍  thanks for the explanations!
