### ISSUE TITLE
pubsub: release flow controller after ack

### ISSUE THREAD

**Issue by jba** [GoogleCloudPlatform/google-cloud-go#870]
Currently, we release the flow controller when the receive callback returns on a message. Instead, do it when the message is acked or nacked.

See #824.

**Comment by Bankq** [comment]
If I understand this correctly, this change will basically "force" client to ack/nack *after* processing the job. Currently I'm acking before processing the job since I don't need the message to redeliver (disposable).

It's not necessarily going to be an issue for me, just trying to clarify this does what I think it does.

**Comment by jba** [comment]
Acking after processing is the norm, so we don't expect this to affect most clients for the worse. But it clearly will be worse for you. You'll observe much higher rates of the Receive callback being invoked.

I'd recommend implementing your own flow control. You can use a weighted semaphore from  [golang.org/x/sync/semaphore](https://godoc.org/golang.org/x/sync/semaphore), as we do in the [flow controller](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/pubsub/flow_controller.go). If you just want to limit the number of active messages, create one with the max size you want:
```
sem := semaphore.NewWeighted(max)
```
Acquire when you start, and release when you're done:
```
err := sem.Acquire(ctx, 1)
// TODO: handle error (context cancellation or deadline)
defer sem.Release(1)
```

**Comment by cristiangraz** [comment]
@jba We always ack, but we don't always send a nack at all depending on what that particular subscriber is doing. In our case if we are depending on a third-party API and something fails (500 error, or a bug on our end) we don't want the message to keep requeueing and burning through our API limits for example. We'll instead just finish processing without actually sending the nack so the message is redelivered after 5-10 mins (or w/e is configured) when the time to acknowledge the message expires.

This worked well before but after this change it looks like it will be a breaking change for us. Given the updates, do you recommend approaching a different way?

**Comment by jba** [comment]
Sorry for breaking you.

Disable our flow controller by setting MaxOutstanding{Messages,Bytes} to -1, then implement your own with a semaphore as I described above.

**Comment by alyosha** [comment]
@jba cc: @pongad @jadekler 
If one of you guys has a minute, I'm looking for a little advice on the below. Thanks in advance 🙏 

---

So I'm in a situation where a portion of the messages my subscriber is pulling cannot be processed immediately and need to be retried later. The time that has to pass until a subsequent retry will succeed varies, but there is a maximum threshold. A subset of these retrying messages will never succeed, but it's unfortunately not possible for me to tell which ones are truly "failed" until that threshold is passed. Other than the retry situation described above, the subscriber `Acks` very quickly.

If I `Nack` right away, I will have repeated, immediate retries for all of the messages that cannot be immediately proccessed, which is obviously not ideal. I cannot `Ack` them either, though, since they have not been successfully processed and I need them to retry again later. 

Originally, I was searching for a way implement exponential backoff for the retries, but I couldn't find a good way to accomplish this (if I'm missing some obvious approach, please let me know). At the time I was using a very old release of the library (`v0.8.0`) and so I ended up implementing the retry logic in the following way:

- Configure `MaxExtension` via environment variable to the desired retry interval
- If a message cannot be processed, but there are no fatal errors, return without calling `Ack` or `Nack`
- Return releases the message from flow control, so next message can be pulled and processed (i.e. no adverse affect on throughput)
- After the duration specified in `MaxExtension` has passed, the message becomes outstanding and retries
- If the max threshold is crossed and a message is still failing to be successfully processed, log and `Ack` (i.e. stop retrying)

It was an imperfect solution, given that the retries happened on a fixed interval, but it seemed like the best option to keep the messages from retrying repeatedly until the maximum threshold was hit. However, given the fact that I now need to bump my version up way past `0.19.0` (where the above change was first introduced), it is looking like I will need to adapt my approach significantly. 

I just want to confirm that you are still recommending the same approach of disabling your flow controller and implementing my own? If you have any other advice for the above-described situation I would also be glad to hear it. More than happy to clarify anything that is unclear.

**Comment by jadekler** [comment]
> I just want to confirm that you are still recommending the same approach of disabling your flow controller and implementing my own?

Yes, that's the best advice we have. Unfortunately Pub/Sub has no native mechanism for supporting this. Holding the message outstanding and implementing a custom flow controller suited to your needs wrt this scenario is still the best answer have.

**Comment by alyosha** [comment]
Thanks a lot for the quick reply. Any ideas about implementing backoff? I started messing around a bit with `apiv1` and trying to hack together an implementation using `ModifyAckDeadline`, but I'm well aware this is a hack. Also apprehensive about using experimental functionality.

Personally, I feel it would be really useful to have some means of delayed redelivery of messages–is there any reason you can't/wouldn't want to support this?

**Comment by jadekler** [comment]
Holding messages outstanding is the only "sort-of-working" way to accomplish the backoff you're suggesting. Even, then, I'll caution you that it's not perfect: you absolutely might receive that message again due to a variety of factors like the message expiring its deadline.

In terms of implementing exponential backoff (as in, getting time values), you can use https://godoc.org/github.com/googleapis/gax-go/v2#Backoff.

**Comment by alyosha** [comment]
@jadekler I know you guys use Gerrit but just wanted to check, what is the best way to float a new proposal?

**Comment by jadekler** [comment]
Thanks for asking. We typically prefer to have a conversation on github issues, though having a reference implementation can certainly help the conversation.

**Comment by alyosha** [comment]
@jadekler I can open a new proposal issue and create a reference PR on my fork for now if that helps? Keep this repo clean

**Comment by alyosha** [comment]
^ created the PR for now, I may be misunderstanding some things but it does work if you want to see the kind of functionality I'm hoping for

**Comment by jadekler** [comment]
@alyosha Thanks - next step is to please file an issue on this repo wherein we can discuss that topic.

Closing this thread now so that we stop spamming old participants. :)
