### ISSUE TITLE
Storage library consumes a huge amount of memory when writing

### ISSUE THREAD

**Issue by vulkoingim** [GoogleCloudPlatform/google-cloud-go#902]
Hello,

While following a huge memory consumption issue in a service we are using (Vault), we discovered the culprit is actually the GCS library. Writing multiple small objects (I assume the same is true for large objects as well), consumes an insane amount of memory. In the included gist you can observe the behaviour.

https://gist.github.com/vulkoingim/320314ae070105769f58dbc1e8e0ba55

![image](https://user-images.githubusercontent.com/5501705/36416901-b61c6caa-162a-11e8-81f3-c6a0fd842208.png)

**Comment by jadekler** [comment]
Thanks for reporting this. We're a little understaffed this week but I'll check this out as soon as I have free cycles.

**Comment by jba** [comment]
The [default chunk size](https://github.com/google/google-api-go-client/blob/a11cf47576f3bc79d7e517bf21887f4c390b1a69/googleapi/googleapi.go#L54) is 8M. Since you have up to 100 of those chunks in memory at once, you will eat a lot of memory.

You could set `Writer.ChunkSize` to a smaller positive value (but it will be rounded up to the nearest 256K). You could also set it to zero, which means there is no chunking&mdash;no client memory devoted to the data; it is streamed directly to the service. In that case, the client will not retry if there is a transient error.

**Comment by vulkoingim** [comment]
Thank you! Reducing the chunk size indeed reduces the memory.

Maybe it can be clarified somewhere else in the documentation as well, since it's not really obvious?
