### ISSUE TITLE
all: support gRPC dial timeout

### ISSUE THREAD

**Issue by jba** [GoogleCloudPlatform/google-cloud-go#946]
It should be possible to express a timeout on connection dial by writing
```
ctx = context.WithTimeout(ctx, 10*time.Second)
c, err := pkg.NewClient(ctx, ...)
```
The problem is that the same context passed to `NewClient` is used in constructing a `TokenSource`, which will repeatedly try to renew creds forever. We'd like to ignore deadlines and cancelation on that TokenSource context.

**Comment by jba** [comment]
@zombiezen Could we use a detachable context for this? Is one available?

**Comment by zombiezen** [comment]
You don't really want this. gRPC client conns shouldn't block on healthy, they should block on first RPC.  That subsequent RPC should have a deadline set, which is the thing you would care about.

**Comment by lhecker** [comment]
Thanks @zombiezen! It makes sense when you consider the possibility of lazy connections.
In my code I often rely on the above, requested feature to make instances fail early on startup if connections cannot be created at all.
I'm fixing my code now wherever I can find this mistake. This could possibly replaced with a simple `SELECTG 1` query I guess?

And maybe this too could be added one day to the documentation. 🙂
I have to say though, that it's a bit weird to be able to pass a context into the function, because it doesn't do what you expect it to do. And that's probably a bit inoptimal API-wise. 😕

**Comment by jba** [comment]
Agreed. We will improve our docs on how to use context.
