### ISSUE TITLE
Using Istio can not perform storage operation

### ISSUE THREAD

**Issue by shinofara** [GoogleCloudPlatform/google-cloud-go#964]
I use google-cloud-go/storage/storage.go
And recently we are verifying the introduction of Istio.

To do that, you need to use http://storage.googleapis.com:443 instead of https://storage.googleapis.com.

Is there a good way to do it?

**Comment by jba** [comment]
Use `option.WithEndpoint`.

**Comment by shinofara** [comment]
https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/storage/reader.go#L62
It looks hard to replace and hard-coded.

**Comment by jba** [comment]
Can you modify reader.go locally and verify that it works? If so, we'll expose it.

**Comment by jba** [comment]
Thanks for the PR! However, I'd like to go about it a little differently. It should be a change at the client level, since it would apply to all objects used by that client.

Did you find you needed to use `option.WithEndpoint` to get the other client methods to work? If so, the client could use that endpoint for read operations. If for some reason only the read is affected (which would surprise me), then we'll think of something else.

Can you point me to some Istio doc that explains why everything needs to go through http and :443 instead of the usual address?

**Comment by jba** [comment]
Thank you for filing this issue. We asked some clarifying questions or suggested a course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
